#pragma once

// Design tokens for the C++ platform shell — ported from
// paleo_workbench/tokens.py (single token vocabulary; light is the base
// palette, dark/high_contrast are curated overrides of the same names).
//
// Parity contract: palette_for()/density_for() replay the frozen oracle in
// tests/cpp/platform/fixtures/platform_services/ (generated by
// tools/oracle/generate_platform_services_fixtures.py). Unknown themes fall
// back to light, unknown densities to comfortable — never throw, mirroring
// the Python coercion.

#include <map>
#include <string>

namespace pwb::platform_services {

enum class ThemeMode { Light, Dark, HighContrast };
enum class Density { Compact, Comfortable };

// Python-facing vocabulary ("light" / "dark" / "high_contrast" /
// "compact" / "comfortable") — the QSettings persistence alphabet.
std::string to_string(ThemeMode mode);
std::string to_string(Density density);

// Exact-value parse (Python ThemeMode(str) semantics); unknown -> Light.
ThemeMode theme_from_string(const std::string& value);
// Exact-value parse; unknown -> Comfortable.
Density density_from_string(const std::string& value);

// Accepts the Python palette_for() normalization: lowercased, '-' -> '_',
// unknown values fall back to light.
ThemeMode theme_from_normalized(const std::string& raw);

// Full token palette for the theme (base + curated overrides merged).
// Values are the Python literals verbatim ("#rrggbb", "rgba(...)",
// "qlineargradient(...)").
std::map<std::string, std::string> palette_for(ThemeMode mode);

// Metric table for the density (unknown -> comfortable, mirroring
// density_tokens()). String members carry QSS shorthand ("6px 12px").
struct DensityMetrics {
    int padding_y = 0;
    int padding_x = 0;
    int btn_height = 0;
    int row_height = 0;
    int toolbar_height = 0;
    int app_bar_height = 0;
    int rail_width = 0;
    int rail_item_size = 0;
    int font_delta = 0;
    std::string tab_padding;
    std::string menu_padding;
    std::string item_padding;
    int combo_item_height = 0;
};

DensityMetrics density_for(Density density);
DensityMetrics density_for(const std::string& density);

// The application version, kept at parity with
// paleo_workbench/__init__.py (__version__, frozen in app_meta.json).
const std::string& app_version();

// The native stylesheet for the platform shell, rendered from the same
// token palette. Scope note (retirement-matrix.md): this is the C++ shell's
// own sheet (menu/toolbar/dock/status bar/inputs), not a byte port of the
// Python workstation's 1800-line page-level sheet — the Python sheets stay
// as the workstation-UI oracle.
std::string build_platform_qss(ThemeMode mode, Density density);

}  // namespace pwb::platform_services
