#!/usr/bin/env python3
"""VIZ-A LAS preview oracle generator.

Freezes two reference results per fixture LAS file:

* ``python_result`` — the REAL production Python preview
  (paleo_workbench/resources/preview_parsers/well_log_parsers.py::las_preview
  + geoviz inspect_las_file + native_backend fast-parse fallback + lasio
  fallback). Nothing under test is stubbed; the paleo_workbench package
  __init__ (PySide6) is bypassed with import trampolines exactly like
  tests/cpp/science/fixtures/welllog/generate_oracle.py.

* ``wle_expected`` — the expectation for the C++ bridge, transcribed from
  the WLE SDK parser contract (well-log-engine/src/io/las.cpp @ f845e7ab,
  rule-by-rule citations below). WLE is the production parser shared by the
  well-log dock, so this is the normative reference for the C++ side —
  never generated by running the new C++ code.

Cases where the two references differ carry an ``adjudication`` note; the
authoritative ledger is docs/development/cpp-viz-a/reconciliation.md.

Negative self-checks:
  * every fixture's sha256 is embedded; consumers verify file integrity;
  * the generator corrupts a copy of each accepted fixture and asserts the
    Python preview changes (frozen expectations are load-bearing);
  * the C++ test flips a byte in memory and asserts the bridge result
    diverges from the frozen expectation.

Run:  python3 tools/oracle/generate_viz_a_las_fixtures.py
Out:  tests/cpp/viz_a/fixtures/las_preview_oracle.json
Deps: lasio, numpy (real reference path); geoviz from the geo-viz-engine
      submodule via PYTHONPATH (set automatically).
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import math
import re
import shutil
import sys
import tempfile
import types
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]
FIXTURE_DIR = REPO_ROOT / "tests" / "cpp" / "viz_a" / "fixtures"
LAS_DIR = FIXTURE_DIR / "las"
A1_PATH = REPO_ROOT / "tests" / "fixtures" / "realdata" / "A1.Las"
GEOVIZ_ROOT = REPO_ROOT / "geo-viz-engine"
OUT_PATH = FIXTURE_DIR / "las_preview_oracle.json"

SCHEMA = "pwb.viz_a.las_preview_oracle/1"

# Adjudication notes (full discussion in reconciliation.md). R-numbers are
# stable identifiers referenced from the ledger and the gap table.
ADJUDICATIONS = {
    "01_normal_multisection": "",  # references agree
    "02_no_curves": "",           # both take the missing-curve-definition branch
    "03_bad_rows": "R3",          # row accounting: >= vs == column count
    "04_custom_null": "",         # exact sentinel matches in both
    "05_descending": "",          # monotonic descending accepted by WLE
    "06_duplicate_depth": "R6",   # duplicates kept by WLE, no diagnostic
    "07_units_desc": "R14",      # unit field: first token (WLE) vs whole trimmed field (legacy)
    "08_中文井名": "",
    "09_wrapped": "R7",           # lasio fallback vs WLE native unwrap
    "10_many_curves": "",
    "11_missing_vers": "R11",     # WLE requires VERS; Python ignores it
    "12_depth_named_md": "R8",    # WLE requires DEPT/DEPTH mnemonic
    "13_mixed_direction": "R12",  # WLE rejects mixed direction entirely
    "14_all_rows_invalid": "R9",  # WLE rejects zero-accepted-row files
    "15_wrap_y": "R10",           # WLE accepts only YES/NO for WRAP
    "16_dlm_comma": "R13",        # WLE has no comma DLM support
    "17_null_tolerance": "R4",    # exact == vs abs_tol=1e-6 sentinel compare
    "a1_real": "",
}

# ---------------------------------------------------------------------------
# Real Python reference path (trampoline-loaded; nothing stubbed).
# ---------------------------------------------------------------------------


def load_python_reference():
    sys.path.insert(0, str(GEOVIZ_ROOT))
    pkg = types.ModuleType("paleo_workbench")
    pkg.__path__ = [str(REPO_ROOT / "paleo_workbench")]
    resources = types.ModuleType("paleo_workbench.resources")
    resources.__path__ = [str(REPO_ROOT / "paleo_workbench" / "resources")]
    parsers = types.ModuleType("paleo_workbench.resources.preview_parsers")
    parsers.__path__ = [
        str(REPO_ROOT / "paleo_workbench" / "resources" / "preview_parsers")
    ]
    viz = types.ModuleType("paleo_workbench.viz")
    viz.__path__ = [str(REPO_ROOT / "paleo_workbench" / "viz")]
    for name, mod in [
        ("paleo_workbench", pkg),
        ("paleo_workbench.resources", resources),
        ("paleo_workbench.resources.preview_parsers", parsers),
        ("paleo_workbench.viz", viz),
    ]:
        sys.modules.setdefault(name, mod)

    def load(name, relpath):
        spec = importlib.util.spec_from_file_location(name, REPO_ROOT / relpath)
        mod = importlib.util.module_from_spec(spec)
        sys.modules[name] = mod
        spec.loader.exec_module(mod)
        return mod

    load("paleo_workbench.native_backend",
         "paleo_workbench/native_backend.py")
    load("paleo_workbench.viz.well_log_api",
         "paleo_workbench/viz/well_log_api.py")
    load("paleo_workbench.resources.preview_parsers.models",
         "paleo_workbench/resources/preview_parsers/models.py")
    load("paleo_workbench.resources.preview_parsers.table_parsers",
         "paleo_workbench/resources/preview_parsers/table_parsers.py")
    return load(
        "paleo_workbench.resources.preview_parsers.well_log_parsers",
        "paleo_workbench/resources/preview_parsers/well_log_parsers.py")


class _Settings:
    """PreviewSettings() defaults as far as las_preview reads them."""

    table_max_rows = 200


def project_preview(result) -> dict:
    """Comparable projection of the Python PreviewResult."""
    return {
        "mode": result.mode,
        "type_label": result.type_label,
        "message": result.message,
        "warning": result.warning,
        "truncated": bool(result.truncated),
        "summary_rows": [list(pair) for pair in result.summary_rows],
        "table_headers": list(result.table_headers),
        "table_rows": [list(row) for row in result.table_rows],
        "data_headers": list(result.data_headers),
        "data_rows": [list(row) for row in result.data_rows],
    }


def run_python_preview(module, las_path: Path, tmp_dir: Path) -> dict:
    import types as _types

    resource = _types.SimpleNamespace(
        path=str(las_path), name=las_path.name, format="las",
        status="active", type="well_log")
    result = module.las_preview(resource, _Settings())
    return project_preview(result)


# ---------------------------------------------------------------------------
# WLE parser contract model — transcribed from
# well-log-engine/src/io/las.cpp @ f845e7ab. Citations per rule.
# ---------------------------------------------------------------------------


def _wle_tokens(line: str):
    return line.split()  # las.cpp tokens_in: space/tab, ASCII


def _wle_parse_number(text: str):
    """las.cpp parse_number (:99-122): NAN/INF words or a full-consume
    from_chars double; returns (value, finite) or None."""
    normalized = text.upper()
    if normalized in {"NAN", "+NAN", "-NAN"}:
        return (float("nan"), False)
    if normalized in {"INF", "+INF", "-INF", "INFINITY", "+INFINITY",
                      "-INFINITY"}:
        return (float("-inf") if normalized[0] == "-" else float("inf"), False)
    # from_chars full-consume: reject trailing junk (e.g. "45,2", "1 2").
    if not re.fullmatch(r"[+-]?(\d+\.?\d*([eE][+-]?\d+)?|\.\d+([eE][+-]?\d+)?)",
                        text):
        return None
    try:
        value = float(text)
    except ValueError:
        return None
    return (value, math.isfinite(value))


def wle_reference(text: str) -> dict:
    """Expected C++ bridge behavior per the WLE SDK contract.

    Returns {"verdict": "accepted", ...preview...} or
    {"verdict": "rejected", ...parse-error preview...}.
    """
    # Section machine: las.cpp:181-197 (first letter V/W/C/A).
    section = "none"
    version = None
    wrapped = False
    wrap_seen = False
    null_sentinel = None
    definitions = []  # (mnemonic, unit, description)
    rows = []

    for raw in text.split("\n"):
        line = raw.split("#", 1)[0].strip(" \t\r")
        if not line:
            continue
        if line.startswith("~"):
            heading = line[1:].strip(" \t\r").upper()
            if not heading:
                section = "none"
            elif heading[0] == "V":
                section = "version"
            elif heading[0] == "W":
                section = "well"
            elif heading[0] == "C":
                section = "curve"
            elif heading[0] == "A":
                section = "ascii"
            else:
                section = "none"
            continue

        if section in ("version", "well"):
            # las.cpp:199-227 — key.VALUE, first token only.
            dot = line.find(".")
            if dot < 0:
                continue
            key = line[:dot].strip(" \t\r").upper()
            value = line[dot + 1:].strip(" \t\r").split(" ")[:1]
            value = value[0] if value else ""
            if key == "VERS" and section == "version":
                parsed = _wle_parse_number(value)
                if parsed is None or not parsed[1]:
                    return _wle_rejected()
                version = parsed[0]
            if key == "WRAP":
                wrap_seen = True
                normalized = value.upper()
                if normalized not in ("YES", "NO"):
                    return _wle_rejected()
                wrapped = normalized == "YES"
            if key == "NULL" and section == "well":
                parsed = _wle_parse_number(value)
                if parsed is None or not parsed[1]:
                    return _wle_rejected()
                null_sentinel = parsed[0]
            continue

        if section == "curve":
            # parse_curve_definition las.cpp:132-151; a malformed line
            # invalidates the whole document (:230-234).
            definition, sep, description = line.partition(":")
            dot = definition.find(".")
            if dot < 0:
                return _wle_rejected()
            mnemonic = definition[:dot].strip(" \t\r")
            if not mnemonic:
                return _wle_rejected()
            unit = definition[dot + 1:].strip(" \t\r").split()[:1]
            unit = unit[0] if unit else ""
            definitions.append((mnemonic, unit, description.strip(" \t\r")))
            continue

        if section == "ascii":
            tokens = _wle_tokens(line)
            if wrapped:
                rows.extend(tokens)  # streamed; re-sliced below
            else:
                rows.append(tokens)

    # las.cpp:249-252 — VERS required, 2.0 <= v < 4.0, >= 2 definitions.
    # The BRIDGE classifies the no-~C case through its own header scan
    # (Python ValueError("LAS contains no curve headers") branch) before
    # the SDK parse, so empty definitions take that preview, not a
    # parse error.
    if not definitions:
        return {
            "verdict": "no_curve_headers",
            "mode": "well_log",
            "type_label": "well_log",
            "message": "",
            "warning": "LAS 文件缺少曲线定义",
            "truncated": False,
            "summary_rows": [["井名", "<stem>"], ["曲线数", "0"],
                             ["采样点", "0"]],
            "table_headers": ["曲线", "单位", "描述"],
            "table_rows": [],
            "data_headers": [],
            "data_rows": [],
        }
    if version is None or not (2.0 <= version < 4.0) or len(definitions) < 2:
        return _wle_rejected()
    # las.cpp:254-264 — DEPT/DEPTH mnemonic required.
    depth_index = next(
        (i for i, (m, _, _) in enumerate(definitions)
         if m.upper() in ("DEPT", "DEPTH")), None)
    if depth_index is None:
        return _wle_rejected()

    accepted = []  # list of per-column values (NaN for nulls)
    if wrapped:
        # las.cpp:325-340 — token stream sliced by column count.
        width = len(definitions)
        offset = 0
        while offset + width <= len(rows):
            accepted.append(rows[offset:offset + width])
            offset += width
        rows = accepted
        accepted = []

    for row in rows:
        # las.cpp:270-323 — full row parse; short/long rows dropped before
        # this point in the non-wrapped path (:341-362).
        if len(row) != len(definitions):
            continue
        parsed = []
        bad = False
        for token in row:
            number = _wle_parse_number(token)
            if number is None:
                bad = True
                break
            parsed.append(number)
        if bad:
            continue
        depth_value, depth_finite = parsed[depth_index]
        if not depth_finite or (
                null_sentinel is not None and depth_value == null_sentinel):
            continue
        accepted.append([
            math.nan if (not v_finite or
                         (null_sentinel is not None and v == null_sentinel))
            else v
            for v, v_finite in parsed
        ])

    if not accepted:
        # las.cpp:365-367.
        return _wle_rejected()

    # las.cpp:368-371 + adapter_common axis_direction: equal neighbors
    # skipped; mixing increase/decrease rejects the document.
    direction_values = []
    prev = None
    for row in accepted:
        d = row[depth_index]
        if prev is not None and d != prev:
            direction_values.append(1 if d > prev else -1)
        prev = d
    if direction_values and (min(direction_values) != max(direction_values)):
        return _wle_rejected()

    # Preview projection (bridge semantics): Python parity over WLE facts.
    # Unit column uses WLE semantics (first token after the dot) so the
    # preview table can never disagree with the dock (R14).
    well_name = _scan_well_name(text)
    truncated = len(definitions) > 200
    return {
        "verdict": "accepted",
        "mode": "well_log",
        "type_label": "well_log",
        "message": "",
        "warning": "曲线列表已按行上限截断" if truncated else "",
        "truncated": truncated,
        "summary_rows": [
            ["井名", well_name],
            ["曲线数", str(len(definitions))],
            ["采样点", str(len(accepted))],
        ],
        "table_headers": ["曲线", "单位", "描述"],
        "table_rows": [
            [m, u, d] for m, u, d in definitions[:200]
        ],
        "data_headers": [m for m, _, _ in definitions],
        "data_rows": [
            [_format_value(v) for v in row] for row in accepted[:100]
        ],
    }


def _scan_well_name(text: str) -> str:
    """~W WELL. value between the first dot and the first colon (Python
    las_preview._well_item parity; the SDK does not surface WELL.)."""
    section = "none"
    for raw in text.split("\n"):
        line = raw.split("#", 1)[0].strip(" \t\r")
        if not line:
            continue
        if line.startswith("~"):
            heading = line[1:].strip(" \t\r").upper()
            if not heading or heading[0] == "A":
                break
            section = {"V": "version", "W": "well", "C": "curve"}.get(
                heading[0] if heading else "", "none")
            continue
        if section != "well":
            continue
        left = line.split(":", 1)[0]
        dot = left.find(".")
        if dot < 0:
            continue
        if left[:dot].strip(" \t\r").upper() != "WELL":
            continue
        value = left[dot + 1:].strip(" \t\r")
        if value:
            return value
    return ""


def _format_value(value: float) -> str:
    if math.isnan(value):
        return "NaN"
    return f"{value:.4f}".rstrip("0").rstrip(".")


def _wle_rejected() -> dict:
    return {
        "verdict": "rejected",
        "mode": "message",
        "type_label": "well_log",
        "message": "LAS 预览失败: ValueError",
        "warning": "LAS 预览失败: ValueError",
        "truncated": False,
        "summary_rows": [],
        "table_headers": [],
        "table_rows": [],
        "data_headers": [],
        "data_rows": [],
    }


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


def main() -> int:
    module = load_python_reference()
    cases = []
    fixtures = sorted(p for p in LAS_DIR.glob("*.las"))
    for path in fixtures + [A1_PATH]:
        case_id = "a1_real" if path == A1_PATH else path.stem
        text = path.read_text(encoding="utf-8", errors="replace")

        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp) / path.name
            shutil.copyfile(path, tmp_path)
            python_result = run_python_preview(module, tmp_path, Path(tmp))
            # Negative self-check: flip single bits in the data half of the
            # file until the frozen reference changes — proves the fixture
            # is load-bearing, not satisfied by any parse of any bytes.
            negative_ok = False
            original = path.read_bytes()
            start = max(0, int(len(original) * 0.5))
            for offset in range(start, len(original)):
                corrupted = bytearray(original)
                corrupted[offset] ^= 0x01
                if bytes(corrupted) == original:
                    continue
                corrupt_path = Path(tmp) / "corrupted.las"
                corrupt_path.write_bytes(bytes(corrupted))
                corrupt_result = run_python_preview(
                    module, corrupt_path, Path(tmp))
                if corrupt_result != python_result:
                    negative_ok = True
                    break

        wle = wle_reference(text)
        wle_projection = {k: v for k, v in wle.items() if k != "verdict"}
        if wle["verdict"] == "no_curve_headers":
            # The stem is a path property; the generator knows it here and
            # the C++ test recomputes it with the same rule.
            wle_projection["summary_rows"][0][1] = path.stem

        cases.append({
            "id": case_id,
            "file": str(path.relative_to(REPO_ROOT)),
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "adjudication": ADJUDICATIONS.get(case_id, ""),
            "wle_verdict": wle["verdict"],
            "python_result": python_result,
            "wle_expected": wle_projection,
            "references_agree": python_result == wle_projection,
            "negative_self_check": negative_ok,
        })

    payload = {
        "schema": SCHEMA,
        "generated_with": {
            "lasio": _module_version("lasio"),
            "numpy": _module_version("numpy"),
            "cpp_fast_las": bool(
                sys.modules.get("paleo_workbench.viz.well_log_api")
                and sys.modules["paleo_workbench.viz.well_log_api"]
                .HAS_CPP_WELL_LOG),
            "geoviz_gitlink": "08851951f3bbc0beb90886adf52e1928f4383c16",
            "wle_gitlink": "f845e7abbbdc3133d28738975d72b2159a2d30f6",
        },
        "cases": cases,
    }
    OUT_PATH.write_text(
        json.dumps(payload, ensure_ascii=False, indent=1) + "\n",
        encoding="utf-8")
    agree = sum(1 for c in cases if c["references_agree"])
    negative = sum(1 for c in cases if c["negative_self_check"])
    print(f"wrote {OUT_PATH} ({len(cases)} cases, "
          f"references agree on {agree}, negative self-checks {negative})")
    return 0


def _module_version(name: str) -> str:
    try:
        return __import__(name).__version__
    except Exception:
        return "unavailable"


if __name__ == "__main__":
    sys.exit(main())
