#!/usr/bin/env python3
"""Frozen Python oracle for the interchange kernel (conv-14).

Imports the REAL paleo_workbench interchange modules (path_safety,
package.manifest, preflight, registry, adapters) and freezes their observed
behavior into a JSON fixture consumed by
libs/interchange/interchange_tests/preflight_test.cpp (ctest target
`interchange.preflight`). Also emits libs/interchange/src/unicode_tables.inc
from the system unicodedata/str.casefold so the C++ NFC/casefold tables share
one source of truth with the oracle. No hand-written expectations: every
"expected" value below is whatever the real Python module returned.
"""

from __future__ import annotations

import base64
import json
import platform
import shutil
import struct
import sys
import tempfile
import unicodedata
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

import _legacy_reference

_legacy_reference.ensure_legacy_reference()  # archived-reference shim

from paleo_workbench.interchange.path_safety import (  # noqa: E402
    UnsafePathError,
    check_collision,
    ensure_within_root,
    is_reserved_or_unsafe,
    safe_relative_path,
    sanitize_filename,
)
from paleo_workbench.interchange.package.manifest import (  # noqa: E402
    MANIFEST_FILENAME,
    MANIFEST_KIND,
    MANIFEST_SCHEMA_VERSION,
    PackageEntry,
    PackageManifest,
    read_manifest,
    write_manifest,
)
from paleo_workbench.interchange.preflight import (  # noqa: E402
    ImportPreflightService,
)
from paleo_workbench.interchange.contracts import (  # noqa: E402
    PreflightFailedError,
)
from paleo_workbench.interchange.registry import (  # noqa: E402
    FormatAdapter,
    InterchangeRegistry,
)
from paleo_workbench.interchange.adapters import build_default_registry  # noqa: E402
from paleo_workbench.interchange.contracts import InspectionResult  # noqa: E402

FIXTURE = (
    REPO_ROOT / "libs" / "interchange" / "interchange_tests"
    / "fixtures" / "interchange_oracle.json"
)
TABLES = REPO_ROOT / "libs" / "interchange" / "src" / "unicode_tables.inc"

# ---------------------------------------------------------------------------
# Unicode tables (.inc) — generated, never hand-written.
# ---------------------------------------------------------------------------


def emit_unicode_tables() -> None:
    decomps: list[tuple[int, tuple[int, ...]]] = []
    for cp in range(0x110000):
        if 0xAC00 <= cp <= 0xD7A3:  # Hangul syllables: algorithmic
            continue
        d = unicodedata.decomposition(chr(cp))
        if not d or d.startswith("<"):
            continue
        seq = tuple(int(part, 16) for part in d.split())
        decomps.append((cp, seq))

    compositions: list[tuple[int, int, int]] = []
    for cp, seq in decomps:
        if len(seq) != 2:
            continue  # singletons recompose to themselves; triples never compose
        composed = unicodedata.normalize("NFC", "".join(chr(c) for c in seq))
        if composed == chr(cp):
            compositions.append((seq[0], seq[1], cp))
    compositions.sort(key=lambda entry: (entry[0], entry[1]))

    ccc_pairs = [
        (cp, unicodedata.combining(chr(cp)))
        for cp in range(0x110000)
        if unicodedata.combining(chr(cp)) != 0
    ]
    ccc_ranges: list[tuple[int, int, int]] = []
    for cp, value in ccc_pairs:
        if ccc_ranges and ccc_ranges[-1][1] == cp - 1 and ccc_ranges[-1][2] == value:
            ccc_ranges[-1] = (ccc_ranges[-1][0], cp, value)
        else:
            ccc_ranges.append((cp, cp, value))

    folds: list[tuple[int, str]] = []
    for cp in range(0x110000):
        ch = chr(cp)
        folded = ch.casefold()
        if folded != ch:
            folds.append((cp, folded))

    lines = [
        "// Generated by tools/oracle/generate_interchange_fixtures.py — DO NOT EDIT.",
        f"// Source: system python3 unicodedata (Unicode {unicodedata.unidata_version})"
        " + str.casefold (full folding).",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace pwb::interchange::unicode_tables {",
        "",
        "struct DecompEntry { std::uint32_t cp; std::uint8_t n; std::uint32_t seq[3]; };",
        f"inline const DecompEntry kCanonicalDecompositions[] = {{",
    ]
    for cp, seq in decomps:
        padded = list(seq) + [0] * (3 - len(seq))
        lines.append(
            "    {{{:#x},{},{{{},{},{}}}}},".format(cp, len(seq), *padded)
        )
    lines += [
        "};",
        "struct ComposeEntry { std::uint32_t a, b, cp; };",
        "inline const ComposeEntry kCanonicalCompositions[] = {",
    ]
    for a, b, cp in compositions:
        lines.append(f"    {{{a:#x},{b:#x},{cp:#x}}},")
    lines += [
        "};",
        "struct CccRange { std::uint32_t first, last; std::uint8_t ccc; };",
        "inline const CccRange kCccRanges[] = {",
    ]
    for first, last, value in ccc_ranges:
        lines.append(f"    {{{first:#x},{last:#x},{value}}},")
    lines += [
        "};",
        "struct FoldEntry { std::uint32_t cp; const char* folded; };",
        "inline const FoldEntry kCasefold[] = {",
    ]
    for cp, folded in folds:
        escaped = "".join(
            f"\\x{byte:02x}" if byte < 0x20 or byte >= 0x7F or byte in (0x22, 0x5C)
            else chr(byte)
            for byte in folded.encode("utf-8")
        )
        lines.append(f'    {{{cp:#x},"{escaped}"}},')
    lines += [
        "};",
        "",
        "}  // namespace pwb::interchange::unicode_tables",
        "",
    ]
    TABLES.parent.mkdir(parents=True, exist_ok=True)
    TABLES.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"unicode_tables.inc: {len(decomps)} decomp, {len(compositions)} compose,"
        f" {len(ccc_ranges)} ccc ranges, {len(folds)} casefold entries"
    )


# ---------------------------------------------------------------------------
# Oracle sections.
# ---------------------------------------------------------------------------


def section_safe_path() -> tuple[list[dict], list[dict]]:
    names_reject = [
        "", "   ", "\t\n", "a\x00b", "cafe\u0301.txt", "A\u030A.txt",
        "\u1100\u1161.txt", "/absolute/path.txt", "/abs", "//x",
        "C:\\windows\\path.txt", "C:/windows/path.txt", "c:x.txt", "\\\\srv\\share",
        "..", "../evil.txt", "a/../../evil.txt", "a/../b.txt", "a\\..\\evil",
        ".", "./", "  /  x", "a/ /b.txt", "a/b /c.txt", "file.txt.", "file.txt. ",
        "...", "con.", "CON", "con.txt", "Con", "NUL.txt", "COM1", "lpt4.ini",
        "bad<name>.txt", 'bad"quote.txt', "pipe|file.txt", "ctrl\x01char.txt",
        "a/" + "x" * 300, "x" * 201, "/".join(["dir"] * 400),
        "\u00a0", "\x1c", "\u3000",
        "\u1f31\u0300.txt", "\u0bc6\u0bbe.txt", "\u09c7\u09d7.txt",
    ]
    names_accept = [
        "data/file.bin", "artifacts/raw/a/b/file.las", "\u6570\u636e/\u6d4b\u4e95/W-001.las",
        "caf\u00e9.txt", "./x.txt", "a/./b.txt", "a//b.txt", "a/b/", "x" * 200,
        "ctrl\x7f.txt", "a/b\x7fc.txt", "..x", ".hidden", "console.txt",
        "\u62a5\u544a v2.json", "a\u2003b.txt", "\u4e2d\u6587 \u76ee\u5f55/x.las",
    ]
    cases: list[dict] = []
    for name in names_reject:
        try:
            safe_relative_path(name)
            raise AssertionError(f"expected rejection: {name!r}")
        except UnsafePathError as exc:
            cases.append(
                {"id": f"reject-{len(cases)}", "name": name, "what": "entry",
                 "ok": False, "path": None, "error": str(exc)}
            )
    for name in names_accept:
        pure = safe_relative_path(name)
        cases.append(
            {"id": f"accept-{len(cases)}", "name": name, "what": "entry",
             "ok": True, "path": str(pure), "error": None}
        )
    # `what` shows up verbatim in the message prefix.
    try:
        safe_relative_path("../x", what="manifest entry")
        raise AssertionError
    except UnsafePathError as exc:
        cases.append({"id": "what-prefix", "name": "../x", "what": "manifest entry",
                      "ok": False, "path": None, "error": str(exc)})
    reserved_flags = [
        ("../x", True), ("CON", True), ("con.txt", True), ("data/file.bin", False),
        ("caf\u00e9.txt", False), ("\x01", True),
    ]
    helpers = [
        {"id": f"reserved-{i}", "name": name, "unsafe": is_reserved_or_unsafe(name)}
        for i, (name, _) in enumerate(reserved_flags)
    ]
    for (name, expected), helper in zip(reserved_flags, helpers):
        assert helper["unsafe"] is expected, name
    return cases, helpers


def section_collision() -> list[dict]:
    sequences = [
        ["Data/file.txt", "data/file.txt"],
        ["a.txt", "a.txt"],
        ["a.txt", "b.txt", "A.TXT"],
        ["\u6570\u636e.txt", "\u6570\u636e.txt"],
        ["ok/x.bin", "ok/y.bin"],
        ["\u00df.txt", "ss.txt"],  # casefold(ß) == "ss" → collision
    ]
    cases = []
    for i, names in enumerate(sequences):
        seen_casefold: set[str] = set()
        seen_nfc: set[str] = set()
        fail_index = None
        error = None
        for index, name in enumerate(names):
            pure = safe_relative_path(name)
            try:
                check_collision(pure, seen_casefold, seen_nfc)
            except UnsafePathError as exc:
                fail_index = index
                error = str(exc)
                break
        cases.append({"id": f"collision-{i}", "names": names,
                      "fail_index": fail_index, "error": error})
    return cases


def section_sanitize() -> list[dict]:
    inputs = [
        ("a/b<c", "export"), ("CON", "export"), ("", "export"), ("  . ", "export"),
        ("x" * 500, "export"), ("cafe\u0301", "export"),
        ("\u62a5\u544a\uff1a\u544a|\u56fe.tif", "export"),
        ("nul.txt", "export"), (".hidden", "export"), (".", "myfallback"),
        ("\u62a5\u544a", "\u5bfc\u51fa"),
    ]
    cases = []
    for stem, fallback in inputs:
        cases.append({"id": f"sanitize-{len(cases)}", "stem": stem,
                      "fallback": fallback,
                      "expected": sanitize_filename(stem, fallback)})
    return cases


def section_unicode() -> list[dict]:
    inputs = [
        "caf\u00e9.txt", "cafe\u0301.txt", "\u212B.txt", "A\u030A.txt",
        "\u00C5.txt", "a\u0301\u0328", "q\u0328\u0301", "\u2126",
        "\uFB01.txt", "\uAC01", "\u1100\u1161", "\uAC00\u11A8", "\u1100\u1161\u11A8",
        "\u0F77", "\u03D2\u0341", "\u6570\u636e/\u6d4b\u4e95.las",
        "\u00df", "\u0130", "\u03a3", "\u0345", "\uFB16",
        "\u4e00\u4e59\u4e8c.las", "a\u0300\u0316\u0317b",
        "\u1f31\u0300", "\u1f31\u0300\u0342", "\u0bc6\u0bbe",
        "\u09c7\u09d7", "a\u0328\u0301", "\u0f77", "s\u0323\u0307",
        "\u1f71\u0345", "\u03b9\u0313\u0300",
    ]
    cases = []
    for text in inputs:
        cases.append({
            "id": f"unicode-{len(cases)}",
            "input": text,
            "nfc": unicodedata.normalize("NFC", text),
            "casefold": text.casefold(),
        })
    return cases


def section_within_root() -> list[dict]:
    """Layouts replayed by both sides in their own temp dirs."""
    scenarios = [
        {"id": "inside-existing",
         "layout": {"dirs": ["pkg/sub"], "files": ["pkg/sub/f.txt"], "symlinks": {}},
         "root": "pkg", "candidate": "pkg/sub/f.txt",
         "expect": "inside", "inside_rel": "sub/f.txt"},
        {"id": "inside-root-itself",
         "layout": {"dirs": ["pkg"], "files": [], "symlinks": {}},
         "root": "pkg", "candidate": "pkg",
         "expect": "inside", "inside_rel": "."},
        {"id": "inside-not-yet-written",
         "layout": {"dirs": ["pkg"], "files": [], "symlinks": {}},
         "root": "pkg", "candidate": "pkg/new.bin",
         "expect": "inside", "inside_rel": "new.bin"},
        {"id": "escape-sibling",
         "layout": {"dirs": ["pkg"], "files": ["outside.txt"], "symlinks": {}},
         "root": "pkg", "candidate": "outside.txt",
         "expect": "escape", "inside_rel": None},
        {"id": "symlink-file",
         "layout": {"dirs": ["pkg"], "files": ["outside.txt"],
                    "symlinks": {"pkg/link.txt": "../outside.txt"}},
         "root": "pkg", "candidate": "pkg/link.txt",
         "expect": "symlink", "inside_rel": None},
        {"id": "escape-through-dirlink",
         "layout": {"dirs": ["pkg", "outside"], "files": ["outside/x.txt"],
                    "symlinks": {"pkg/dirlink": "../outside"}},
         "root": "pkg", "candidate": "pkg/dirlink/x.txt",
         "expect": "escape", "inside_rel": None},
    ]
    checked = []
    work = Path(tempfile.mkdtemp(prefix="pwb-oracle-root-"))
    try:
        for scenario in scenarios:
            base = work / scenario["id"]
            base.mkdir()
            for rel in scenario["layout"]["dirs"]:
                (base / rel).mkdir(parents=True, exist_ok=True)
            for rel in scenario["layout"]["files"]:
                (base / rel).write_text("x", encoding="utf-8")
            for link, target in scenario["layout"]["symlinks"].items():
                (base / link).symlink_to(target)
            outcome = {"inside": None, "symlink": None, "escape": None}
            prefix = ""
            try:
                resolved = ensure_within_root(base / scenario["root"],
                                              base / scenario["candidate"])
                outcome["inside"] = resolved.relative_to((base / scenario["root"]).resolve()).as_posix()
            except UnsafePathError as exc:
                message = str(exc)
                prefix = message.split(":", 1)[0]
                if message.startswith("symlink rejected"):
                    outcome["symlink"] = message
                elif message.startswith("path escapes package root"):
                    outcome["escape"] = message
                else:
                    raise AssertionError(f"unexpected message: {message}") from exc
            scenario["message_prefix"] = prefix
            expect = scenario["expect"]
            assert outcome[expect] is not None or expect == "inside", scenario
            if expect == "inside":
                assert outcome["inside"] == scenario["inside_rel"], scenario
            checked.append({**scenario, "observed_rel": outcome["inside"]})
    finally:
        shutil.rmtree(work, ignore_errors=True)
    return checked


def section_manifest() -> dict:
    minimal = PackageManifest()
    full = PackageManifest(
        project_name="demo",
        project_file="demo.paleo.json",
        created_at="2026-09-17T08:00:00+00:00",
        application_version="0.2.17a0",
        entries=[
            PackageEntry(path="demo.paleo.json", sha256="ab" * 32,
                         size_bytes=123, kind="project"),
            PackageEntry(path="\u6570\u636e/\u6d4b\u4e95/w.las", sha256="cd" * 32,
                         size_bytes=9, kind="artifact"),
        ],
        external_dependencies=[
            {"version_id": "v1", "asset": "ext", "path": "/outside/x.las",
             "size_bytes": 5, "policy": "keep"},
        ],
        missing_dependencies=[
            {"version_id": "v9", "asset": "gone", "path": "/gone/x.las",
             "reason": "managed payload \u4e0d\u5b58\u5728"},
        ],
        generated_outputs=["v-out-1", "v-out-2"],
        provenance={"runs": [{"id": "r1", "operation": "interchange.import",
                              "status": "completed"}],
                    "run_count": 1,
                    "\u5907\u6ce8": "oracle"},
        options={"external_policy": "keep", "include_outputs_only": False,
                 "include_formats": None},
        total_size_bytes=132,
    )

    build = [
        {"id": "manifest-default", "dict": minimal.to_dict(), "dumps": minimal.dumps()},
        {"id": "manifest-full", "dict": full.to_dict(), "dumps": full.dumps()},
    ]

    def _from_dict(data: dict) -> dict:
        try:
            revived = PackageManifest.from_dict(data)
            return {"input": data, "ok": True, "error": None,
                    "dict": revived.to_dict()}
        except (ValueError, TypeError) as exc:
            return {"input": data, "ok": False, "error": str(exc),
                    "dict": None}

    bad_versions = []
    for raw in (True, False, "2", 2.5, None):
        data = full.to_dict()
        data["schema_version"] = raw
        bad_versions.append(_from_dict(data))
    def _coerce_variant(**field_overrides) -> dict:
        data = full.to_dict()
        entry = dict(data["entries"][1])
        entry.update(field_overrides)
        data["entries"] = [entry]
        return data

    coerce_total = full.to_dict()
    coerce_total["total_size_bytes"] = "7"
    coerce_created = full.to_dict()
    coerce_created["created_at"] = 99
    from_dict = [
        {"id": "roundtrip-full", **_from_dict(full.to_dict())},
        {"id": "defaults-empty", **_from_dict({})},
        {"id": "coerce-size-str", **_from_dict(_coerce_variant(size_bytes="5"))},
        {"id": "coerce-size-float", **_from_dict(_coerce_variant(size_bytes=2.9))},
        {"id": "coerce-size-bool", **_from_dict(_coerce_variant(size_bytes=True))},
        {"id": "coerce-size-bad", **_from_dict(_coerce_variant(size_bytes="abc"))},
        {"id": "coerce-size-null", **_from_dict(_coerce_variant(size_bytes=None))},
        {"id": "coerce-kind-null", **_from_dict(_coerce_variant(kind=None))},
        {"id": "coerce-path-int", **_from_dict(_coerce_variant(path=12345))},
        {"id": "coerce-total-str", **_from_dict(coerce_total)},
        {"id": "coerce-created-int", **_from_dict(coerce_created)},
        {"id": "schema-true", **bad_versions[0]},
        {"id": "schema-false", **bad_versions[1]},
        {"id": "schema-str", **bad_versions[2]},
        {"id": "schema-float", **bad_versions[3]},
        {"id": "schema-null", **bad_versions[4]},
    ]

    def _validate(data: dict) -> dict:
        manifest = PackageManifest.from_dict(data)
        try:
            manifest.validate_paths()
            return {"input": data, "ok": True, "error": None}
        except UnsafePathError as exc:
            return {"input": data, "ok": False, "error": str(exc)}

    def _variant(**overrides) -> dict:
        data = full.to_dict()
        data.update(overrides)
        return data

    dup = full.to_dict()
    dup["entries"] = [
        {"path": "a/b.txt", "sha256": "00" * 32, "size_bytes": 1, "kind": "artifact"},
        {"path": "a/b.txt", "sha256": "01" * 32, "size_bytes": 2, "kind": "artifact"},
    ]
    casefold_dup = full.to_dict()
    casefold_dup["entries"] = [
        {"path": "A/B.txt", "sha256": "00" * 32, "size_bytes": 1, "kind": "artifact"},
        {"path": "a/b.txt", "sha256": "01" * 32, "size_bytes": 2, "kind": "artifact"},
    ]
    validate = [
        {"id": "validate-ok", **_validate(full.to_dict())},
        {"id": "validate-traversal",
         **_validate(_variant(entries=[{"path": "../evil.txt", "sha256": "00" * 32,
                                        "size_bytes": 1, "kind": "artifact"}]))},
        {"id": "validate-absolute",
         **_validate(_variant(entries=[{"path": "/etc/passwd", "sha256": "00" * 32,
                                        "size_bytes": 1, "kind": "artifact"}]))},
        {"id": "validate-dup-nfc", **_validate(dup)},
        {"id": "validate-casefold", **_validate(casefold_dup)},
        {"id": "validate-project-file",
         **_validate(_variant(project_file="../paleo.json"))},
        {"id": "validate-empty-project-file-ok",
         **_validate(_variant(project_file=""))},
    ]

    # write + read round trip through the real filesystem helpers.
    work = Path(tempfile.mkdtemp(prefix="pwb-oracle-manifest-"))
    try:
        target = write_manifest(full, work)
        assert target == work / MANIFEST_FILENAME
        reread = read_manifest(work)
        roundtrip = reread.to_dict()
        # created_at survives verbatim; dump text must be byte-identical too
        assert read_manifest(work).dumps() == full.dumps()
    finally:
        shutil.rmtree(work, ignore_errors=True)

    return {
        "filename": MANIFEST_FILENAME,
        "kind": MANIFEST_KIND,
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "build": build,
        "from_dict": from_dict,
        "validate": validate,
        "entry_paths": [{"id": "entry-paths-full",
                         "paths": sorted(full.entry_paths())}],
        "write_read_roundtrip": {"dict": roundtrip, "dumps": full.dumps()},
    }


# ---------------------------------------------------------------------------
# Preflight decision tree: real ImportPreflightService over stub adapters.
# ---------------------------------------------------------------------------

TIFF_CONTENT = b"II*\x00" + b"\x00" * 100
GPKG_CONTENT = b"SQLite format 3\x00" + b"\x00" * 52 + b"GPKG" + b"\x00" * 40
SHP_CONTENT = struct.pack(">I", 9994) + b"\x00" * 100
BINARY_CONTENT = bytes(range(256)) * 4
PLAIN_CONTENT = "plain notes\nsecond line\nnothing special\n".encode("utf-8")


def _las_content() -> bytes:
    lines = [
        "~VERSION INFORMATION",
        "VERS. 2.0 : CWLS LOG ASCII STANDARD",
        "WRAP. NO : ONE LINE PER DEPTH STEP",
        "~WELL INFORMATION",
        "STRT.M 100.0",
        "STOP.M 109.5",
        "STEP.M 0.5",
        "NULL. -999.25",
        "WELL. W-001",
        "~CURVE INFORMATION",
        "DEPT.M : depth",
        "GR.GAPI : gamma",
        "~A",
    ]
    return ("\n".join(lines) + "\n").encode("utf-8")


def _zip_content() -> bytes:
    import io

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as bundle:
        info = zipfile.ZipInfo("note.txt", date_time=(1980, 1, 1, 0, 0, 0))
        bundle.writestr(info, "hi")
    return buffer.getvalue()


class _StubAdapter(FormatAdapter):
    def __init__(self, spec: dict) -> None:
        self.format_id = spec["format_id"]
        self.display_name = spec.get("display_name", self.format_id)
        self.extensions = tuple(spec["extensions"])
        self._import = bool(spec["import"])
        self._notes = spec.get("notes", "")
        self._inspection = spec.get("inspect")

    def capability(self):
        from paleo_workbench.interchange.contracts import FormatCapability

        return FormatCapability(read=self._import, inspect=self._import,
                                import_data=self._import,
                                notes=self._notes)

    def inspect(self, path):
        spec = self._inspection or {}
        return InspectionResult(
            format_id=self.format_id,
            ok=bool(spec.get("ok", True)),
            size_bytes=int(spec.get("size_bytes", 0)),
            metadata=dict(spec.get("metadata", {})),
            warnings=list(spec.get("warnings", ())),
            errors=list(spec.get("errors", ())),
        )


PATH_SENTINEL = "<PATH>"


def section_preflight() -> dict:
    cases: list[dict] = []
    work = Path(tempfile.mkdtemp(prefix="pwb-oracle-preflight-"))
    try:
        def add_case(case_id: str, file_kind: str, file_name: str,
                     content: bytes, registry_mode: str,
                     stub_specs: list[dict] | None) -> dict:
            path = work / file_name
            if file_kind == "file":
                path.write_bytes(content)
            elif file_kind == "dir":
                path.mkdir()
            registry = InterchangeRegistry()
            if registry_mode == "default":
                registry = build_default_registry()
            else:
                for spec in stub_specs or []:
                    registry.register(_StubAdapter(spec))
            service = ImportPreflightService(registry)
            report = service.inspect(path)
            payload = report.to_dict()
            payload["path"] = PATH_SENTINEL
            cases.append({
                "id": case_id,
                "fs": {"kind": file_kind,
                       "suffix": path.suffix.lower().lstrip("."),
                       "content_b64": base64.b64encode(content).decode("ascii")
                       if file_kind == "file" else ""},
                "file_name": file_name,
                "registry": registry_mode,
                "stub": stub_specs or [],
                "report": payload,
            })
            return cases[-1]

        add_case("missing-file", "missing", "nope.las", b"", "default", None)
        add_case("directory", "dir", "sample_dir", b"", "default", None)
        add_case("format-unknown", "file", "mystery.bin", BINARY_CONTENT,
                 "default", None)
        add_case("las-managed-ok", "file", "w.las", _las_content(), "stub", [
            {"format_id": "las", "display_name": "LAS \u6d4b\u4e95\u66f2\u7ebf",
             "extensions": ["las"], "import": True, "notes": "",
             "inspect": {"ok": True, "size_bytes": 4321,
                         "metadata": {"well_name": "W-001"},
                         "warnings": [], "errors": []}},
        ])
        add_case("las-inspect-warning", "file", "w2.las", _las_content(), "stub", [
            {"format_id": "las", "extensions": ["las"], "import": True,
             "inspect": {"ok": True, "size_bytes": 100,
                         "warnings": ["\u91cd\u590d\u66f2\u7ebf\u52a9\u8bb0\u540d: GR"],
                         "errors": []}},
        ])
        add_case("las-inspect-error", "file", "w3.las", _las_content(), "stub", [
            {"format_id": "las", "extensions": ["las"], "import": True,
             "inspect": {"ok": False, "size_bytes": 0,
                         "warnings": ["\u7f16\u7801\u53ef\u7591"],
                         "errors": ["LAS \u5934\u89e3\u6790\u5931\u8d25: boom"]}},
        ])
        add_case("import-unavailable-notes", "file", "r.tif", TIFF_CONTENT,
                 "stub", [
            {"format_id": "raster", "extensions": ["tif", "tiff", "img", "grd"],
             "import": False,
             "notes": "GDAL/rasterio \u4e0d\u53ef\u7528",
             "inspect": {"ok": True, "size_bytes": 777, "warnings": [],
                         "errors": []}},
        ])
        add_case("import-unavailable-default-note", "file", "r.tiff",
                 TIFF_CONTENT, "stub", [
            {"format_id": "raster", "extensions": ["tif", "tiff"], "import": False,
             "notes": "", "inspect": {"ok": True, "size_bytes": 55}},
        ])
        add_case("extension-content-mismatch", "file", "surprise.tif",
                 TIFF_CONTENT, "stub", [
            {"format_id": "fake_tiff_host", "extensions": ["tif"], "import": True,
             "inspect": {"ok": True, "size_bytes": 1}},
        ])
        add_case("sniff-advisory", "file", "notes.csv", _zip_content(), "stub", [
            {"format_id": "csv", "extensions": ["csv"], "import": True,
             "inspect": {"ok": True, "size_bytes": 77, "warnings": [],
                         "errors": []}},
        ])
        add_case("extension-mismatch", "file", "w.tif", _las_content(), "stub", [
            {"format_id": "las", "extensions": ["las"], "import": True,
             "inspect": {"ok": True, "size_bytes": 64}},
        ])
        add_case("alias-gpkg", "file", "layers.gpkg", GPKG_CONTENT, "stub", [
            {"format_id": "vector_gdal",
             "extensions": ["shp", "gpkg", "kml", "gml", "geojson", "tab", "mif"],
             "import": False,
             "notes": "GDAL (osgeo) \u4e0d\u53ef\u7528\uff1avendored \u6784\u5efa\u672a\u5b89\u88c5",
             "inspect": {"ok": True, "size_bytes": 4096}},
        ])
        add_case("alias-shp-inspect-error", "file", "pts.shp", SHP_CONTENT,
                 "stub", [
            {"format_id": "vector_gdal", "extensions": ["shp", "gpkg"],
             "import": True,
             "inspect": {"ok": False, "size_bytes": 0, "warnings": [],
                         "errors": ["Shapefile sidecar \u4e0d\u5b8c\u6574"]}},
        ])
        add_case("plain-text-unregistered-ext", "file", "notes.txt",
                 PLAIN_CONTENT, "stub", [
            {"format_id": "tsv", "extensions": ["tsv", "txt"], "import": True,
             "inspect": {"ok": True, "size_bytes": 42}},
        ])

        # plan(): failure message and default plan_import payloads.
        plans = []

        def add_plan(plan_id: str, case_id: str, *, managed=None,
                     asset_name=None, options=None) -> None:
            case = next(c for c in cases if c["id"] == case_id)
            path = work / case["file_name"]
            if case["fs"]["kind"] == "file":
                path.write_bytes(base64.b64decode(case["fs"]["content_b64"]))
            elif case["fs"]["kind"] == "dir":
                path.mkdir(exist_ok=True)
            registry = InterchangeRegistry()
            if case["registry"] == "default":
                registry = build_default_registry()
            else:
                for spec in case["stub"]:
                    registry.register(_StubAdapter(spec))
            service = ImportPreflightService(registry)
            kwargs = {}
            if managed is not None:
                kwargs["managed"] = managed
            if asset_name is not None:
                kwargs["asset_name"] = asset_name
            if options is not None:
                kwargs["options"] = options
            entry = {"id": plan_id, "case": case_id,
                     "managed": managed, "asset_name": asset_name,
                     "options": options or {}}
            try:
                plan = service.plan(path, **kwargs)
                payload = plan.to_dict()
                payload["source_path"] = PATH_SENTINEL
                entry.update({"ok": True, "plan": payload, "error": None})
            except PreflightFailedError as exc:
                entry.update({"ok": False, "plan": None, "error": str(exc)})
            plans.append(entry)

        add_plan("plan-ok-managed", "las-managed-ok", asset_name="W-1")
        add_plan("plan-ok-default-name", "las-managed-ok")
        add_plan("plan-link-external", "las-managed-ok", managed=False,
                 asset_name="W-1")
        add_plan("plan-unsupported", "las-inspect-error", asset_name="W")
        add_plan("plan-fail-unknown", "format-unknown")
        add_plan("plan-fail-mismatch", "extension-content-mismatch")
        add_plan("plan-with-options", "las-managed-ok", asset_name="W-2",
                 options={"normalize": True})
        add_plan("plan-empty-asset-name", "las-managed-ok", asset_name="")
        return {"cases": cases, "plans": plans}
    finally:
        shutil.rmtree(work, ignore_errors=True)


def section_fuzz_nfc() -> list[dict]:
    """Deterministic composition stress: random code-point sequences from a
    starter/mark pool (Greek marks, Tamil/Bengali starter pairs, CCC 202/220/
    230/240 marks, jamo), frozen through REAL unicodedata.normalize."""
    import random

    rng = random.Random(20260917)
    pool = [
        "a", "e", "q", "\u03b9", "\u03b1", "\u03bf", "\u03c5",
        "\u0300", "\u0301", "\u0313", "\u0314", "\u0342", "\u0345",
        "\u0323", "\u0307", "\u0328", "\u0316", "\u05ae",
        "\u0bc6", "\u0bc7", "\u0bbe", "\u0bd7", "\u0bcd",
        "\u09c7", "\u09be", "\u09d7",
        "\u1100", "\u1161", "\u11a8", "\uac00",
        "\u4e2d", "x", "-",
    ]
    cases = []
    seen = set()
    for i in range(300):
        length = rng.randint(2, 6)
        text_input = "".join(rng.choice(pool) for _ in range(length))
        if text_input in seen:
            continue
        seen.add(text_input)
        cases.append({
            "id": f"fuzznfc-{i}",
            "input": text_input,
            "nfc": unicodedata.normalize("NFC", text_input),
            "casefold": text_input.casefold(),
        })
    return cases


def section_fuzz() -> list[dict]:
    """Deterministic adversarial corpus: random Unicode + ASCII nasties run
    through the REAL safe_relative_path. Seed pinned for reproducibility."""
    import random

    rng = random.Random(20260917)
    pool = [
        "a", "b", ".", "..", "/", "\\", ":", "|", "?", "*", "<", ">", '"',
        "\x00", "\x01", "\x7f", " ", "\t", "\u00e9", "\u0301", "\u0041\u030a",
        "\u4e2d", "\u6587", "\uac00", "\u1100", "\u1161", "\u11a8",
        "\u00df", "\u03a3", "\u0130", "\ufb01", "\u212b", "\u2126",
        "con", "nul", "com1", "lpt4", "txt", "0123456789",
        "\u00a0", "\u3000", "\u2003", "\x1c", "\x1d", "\u2028",
        "\u1f31", "\u0bc6\u0bbe", "\u09c7\u09d7",
    ]
    cases = []
    for i in range(200):
        length = rng.randint(0, 14)
        name = "".join(rng.choice(pool) for _ in range(length))
        if name in {case["name"] for case in cases}:
            continue
        try:
            pure = safe_relative_path(name)
            cases.append({"id": f"fuzz-{i}", "name": name, "ok": True,
                          "path": str(pure), "error": None})
        except UnsafePathError as exc:
            cases.append({"id": f"fuzz-{i}", "name": name, "ok": False,
                          "path": None, "error": str(exc)})
    return cases


def section_registry() -> list[dict]:
    cases = []

    class _Demo(FormatAdapter):
        format_id = "demo"
        display_name = "demo"
        extensions = ("demo",)

        def capability(self):
            from paleo_workbench.interchange.contracts import FormatCapability

            return FormatCapability()

        def inspect(self, path):
            raise NotImplementedError

    registry = InterchangeRegistry()
    registry.register(_Demo())
    try:
        registry.register(_Demo())
        raise AssertionError("expected duplicate rejection")
    except ValueError as exc:
        cases.append({"id": "duplicate", "error": str(exc)})
    registry.register(_Demo(), replace=True)
    cases.append({"id": "replace", "get_demo": registry.get("demo") is not None,
                  "ext_lookup": registry.adapter_for_extension(Path("x.demo")).format_id})

    class _Blank(FormatAdapter):
        format_id = ""
        display_name = ""
        extensions = ("x",)

        def capability(self):
            raise NotImplementedError

        def inspect(self, path):
            raise NotImplementedError

    try:
        registry.register(_Blank())
        raise AssertionError("expected blank rejection")
    except ValueError as exc:
        cases.append({"id": "blank", "error": str(exc)})
    return cases


def main() -> None:
    emit_unicode_tables()
    safe_path, reserved = section_safe_path()
    payload = {
        "meta": {
            "unicode": unicodedata.unidata_version,
            "python": platform.python_version(),
            "generator": "tools/oracle/generate_interchange_fixtures.py",
        },
        "adapters": [
            {"format_id": row["format_id"], "display_name": row["display_name"],
             "extensions": list(row["extensions"]), "import": bool(row["import"]),
             "notes": row["notes"]}
            for row in build_default_registry().capability_matrix()
        ],
        "safe_path": safe_path,
        "reserved_helper": reserved,
        "collision": section_collision(),
        "sanitize": section_sanitize(),
        "unicode": section_unicode(),
        "fuzz_nfc": section_fuzz_nfc(),
        "within_root": section_within_root(),
        "manifest": section_manifest(),
        "preflight": section_preflight(),
        "registry": section_registry(),
        "fuzz": section_fuzz(),
    }
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(json.dumps(payload, ensure_ascii=False, indent=1),
                       encoding="utf-8")
    counts = {
        "safe_path": len(payload["safe_path"]),
        "collision": len(payload["collision"]),
        "sanitize": len(payload["sanitize"]),
        "unicode": len(payload["unicode"]),
        "fuzz_nfc": len(payload["fuzz_nfc"]),
        "within_root": len(payload["within_root"]),
        "manifest_build": len(payload["manifest"]["build"]),
        "manifest_from_dict": len(payload["manifest"]["from_dict"]),
        "manifest_validate": len(payload["manifest"]["validate"]),
        "preflight_cases": len(payload["preflight"]["cases"]),
        "preflight_plans": len(payload["preflight"]["plans"]),
        "registry": len(payload["registry"]),
        "fuzz": len(payload["fuzz"]),
    }
    print(f"oracle → {FIXTURE.relative_to(REPO_ROOT)}: {counts}")


if __name__ == "__main__":
    main()
