#!/usr/bin/env python3
"""Oracle for the CONV-22 geomodel contract layer.

Freezes the pure contract surface of:
  * paleo_workbench.viz.geomodel.domain   (objects / meta / assembly / stats)
  * paleo_workbench.viz.geomodel.qc       (severity ladder / audits / gate)
  * paleo_workbench.viz.geomodel.exporters(V2 writers + read-back validators
                                           + legacy structured grid)
  * paleo_workbench.viz.geomodel.advisor  (borehole / coplanar-fault rules)
  * paleo_workbench.viz.geomodel.lithology(tables + sample_log_values)
  * paleo_workbench.viz.geomodel.builders (dataclass constructors only —
    the geometry kernels were frozen by CONV-12)

Every expectation is produced by calling the real modules — nothing is
hand-written. Run with the conv-12 oracle venv (numpy + scipy):
  PYTHONPATH=<repo root> oracle-venvs/conv12/bin/python \
      tools/oracle/generate_geomodel_contract_fixtures.py

Fixture protocol (same as CONV-21):
  * cases: {"id", "fn", "input", "expect"}; expect = {"result": ...} or
    {"raises": <python class name>, "message": str(exc)}
  * numeric arrays use null for NaN (input specs and outputs alike);
  * binary payloads are {"b64": ...};
  * file contents are frozen inline (text or b64) — no $FX needed since
    names passed to the readers/validators are fixed relative names;
  * STL bytes → {"b64"}; sidecar JSON → parsed dict (byte-exactness of the
    provenance file is covered by the dict itself + its key order).
"""

from __future__ import annotations

import base64
import json
import math
import sys
import tempfile
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from paleo_workbench.env_bootstrap import ensure_geoviz_on_path  # noqa: E402

ensure_geoviz_on_path()

from paleo_workbench.viz.geomodel import advisor  # noqa: E402
from paleo_workbench.viz.geomodel import builders  # noqa: E402
from paleo_workbench.viz.geomodel import domain  # noqa: E402
from paleo_workbench.viz.geomodel import exporters  # noqa: E402
from paleo_workbench.viz.geomodel import lithology  # noqa: E402
from paleo_workbench.viz.geomodel import qc as gm_qc  # noqa: E402

OUT_DIR = REPO_ROOT / "libs" / "geomodel" / "geomodel_tests" / "fixtures"
OUT = OUT_DIR / "geomodel_contract_oracle.json"
LOWER_INC = (REPO_ROOT / "libs" / "geomodel" / "src" / "lower_map.inc")


def write_lower_map():
    """str.lower() table: every code point whose .lower() differs, emitted
    as (cp, utf8-string) pairs. Generated by the same Python that freezes
    the oracle (str.lower != str.casefold, e.g. ß/ﬀ)."""
    rows = []
    for cp in range(0x110000):
        lo = chr(cp).lower()
        if lo != chr(cp):
            esc = "".join(f"\\x{c:02x}" for c in lo.encode("utf-8"))
            rows.append(f'    {{0x{cp:05X}u, "{esc}"}},')
    body = "// generated by generate_geomodel_contract_fixtures.py — str.lower()\n"
    body += "// map for code points where lower(cp) != cp\n"
    body += "\n".join(rows) + "\n"
    LOWER_INC.write_text(body, encoding="utf-8")
    return len(rows)

# Set by main(): readers/validators report absolute paths in their error
# messages; they are frozen with the "$FX" placeholder (replaced back to the
# test's own fixture dir by the C++ runner, same convention as CONV-21).
TMP_DIR: Path | None = None


def fx_fix(entry):
    if TMP_DIR is None:
        return
    text = json.dumps(entry, ensure_ascii=False)
    entry.clear()
    entry.update(json.loads(text.replace(str(TMP_DIR), "$FX")))


# ---------------------------------------------------------------------------
# JSON conversion — NaN in numeric arrays <-> null; bytes -> {"b64"}
# ---------------------------------------------------------------------------

def J(x):
    if isinstance(x, np.ndarray):
        return J(x.tolist())
    if isinstance(x, np.generic):
        return J(x.item())
    if isinstance(x, float):
        if math.isnan(x):
            return None
        if x == math.inf:
            return "inf"
        if x == -math.inf:
            return "-inf"
        return x
    if isinstance(x, dict):
        return {str(k): J(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [J(v) for v in x]
    if isinstance(x, (bytes, bytearray)):
        return {"b64": base64.b64encode(bytes(x)).decode("ascii")}
    if isinstance(x, Path):
        return str(x)
    return x


def arr(x, dtype=np.float64):
    """JSON list -> ndarray; null inside arrays becomes NaN."""
    if x is None:
        return None
    def conv(v):
        return math.nan if v is None else v
    def deep(v):
        if isinstance(v, list):
            return [deep(e) for e in v]
        return conv(v)
    return np.asarray(deep(x), dtype=dtype)


def iarr(x):
    if x is None:
        return None
    return np.asarray(x, dtype=np.int64)


def opt(x):
    """spec value: explicit null -> None (Python None), missing handled by get()."""
    return x


# ---------------------------------------------------------------------------
# spec -> real domain object (constructor kwargs mirror)
# ---------------------------------------------------------------------------

def prov_of(spec):
    p = spec.get("provenance")
    if p is None:
        return domain.Provenance()
    return domain.Provenance(
        source_kind=p.get("source_kind", "derived"),
        source_version_ids=tuple(p.get("source_version_ids", ())),
        created_from=p.get("created_from", ""),
        demo=bool(p.get("demo", False)),
    )


def common_kwargs(spec):
    return dict(
        object_id=spec["object_id"],
        name=spec["name"],
        crs=spec.get("crs", "unknown"),
        vertical_domain=spec.get("vertical_domain", "depth"),
        unit=spec.get("unit", "m"),
        provenance=prov_of(spec),
        version=spec.get("version", 1),
    )


def construct(spec):
    kind = spec["kind"]
    kw = common_kwargs(spec)
    if kind == "well":
        return domain.WellTrajectory(
            stations=arr(spec.get("stations", [])),
            representation=spec.get("representation", "measured"),
            z_unit=spec.get("z_unit"),
            well_asset_id=spec.get("well_asset_id", ""),
            formation_tops=tuple(
                (str(t[0]), float(t[1])) for t in spec.get("formation_tops", ())
            ),
            **kw,
        )
    if kind == "horizon":
        return domain.HorizonSurface(
            z_grid=arr(spec.get("z_grid", [])),
            origin=tuple(spec.get("origin", (0.0, 0.0))),
            spacing=tuple(spec.get("spacing", (1.0, 1.0))),
            grid_crs=spec.get("grid_crs", ""),
            horizon_asset_id=spec.get("horizon_asset_id", ""),
            confidence=arr(spec["confidence"]) if "confidence" in spec else None,
            attributes=tuple(
                (n, arr(a)) for n, a in spec.get("attributes", ())
            ),
            **kw,
        )
    if kind == "fault":
        zd = spec.get("z_extent")
        sd = spec.get("strike_dip")
        return domain.FaultSurface(
            verts=arr(spec.get("verts", [])),
            faces=iarr(spec.get("faces", [])),
            representation=spec.get("representation", "triangulated_3d"),
            trace_xy=arr(spec["trace_xy"]) if "trace_xy" in spec else None,
            z_extent=tuple(zd) if zd is not None else None,
            throw_m=spec.get("throw_m"),
            strike_dip=tuple(sd) if sd is not None else None,
            fault_asset_id=spec.get("fault_asset_id", ""),
            intersects_horizons=tuple(spec.get("intersects_horizons", ())),
            **kw,
        )
    if kind == "volume":
        return domain.StratigraphicVolume(
            verts=arr(spec.get("verts", [])),
            faces=iarr(spec.get("faces", [])),
            top_id=spec.get("top_id", ""),
            base_id=spec.get("base_id", ""),
            boundary=arr(spec["boundary"]) if "boundary" in spec else None,
            formation=spec.get("formation", ""),
            facies=iarr(spec["facies"]) if "facies" in spec else None,
            properties=tuple(
                (n, arr(a)) for n, a in spec.get("properties", ())
            ),
            cell_mesh=spec.get("cell_mesh"),
            quality=dict(spec.get("quality", {})),
            **kw,
        )
    if kind == "tunnel":
        return domain.TunnelSection(
            path=arr(spec.get("path", [])),
            radius=spec.get("radius", 3.0),
            **kw,
        )
    if kind == "measure":
        return domain.MeasurementRecord(
            measurement_kind=spec.get("measurement_kind", "distance"),
            points=arr(spec.get("points", [])),
            result=spec.get("result"),
            extra=dict(spec.get("extra", {})),
            **kw,
        )
    raise AssertionError(f"unknown kind {kind}")


def mutate(obj, spec):
    """Post-construction mutations (frozen-by-convention bypass) — the QC
    crash/report paths the constructor guards against."""
    for m in spec.get("_mutate", ()):
        target, idx, val = m["field"], m.get("index"), m.get("value")
        a = getattr(obj, target)
        v = math.nan if val is None else val
        if target in ("stations", "verts", "path", "points", "z_grid",
                      "confidence"):
            if isinstance(idx, int):
                a.flat[idx] = v
            else:
                a[tuple(idx)] = v
        elif target == "faces":
            if isinstance(idx, int):
                a.flat[idx] = int(v)
            else:
                a[tuple(idx)] = int(v)
        else:
            raise AssertionError(f"mutate target {target}")
    return obj


def spec_of(obj):
    """domain object -> constructor spec (arrays -> JSON lists)."""
    kind = obj.kind()
    s = {
        "kind": kind,
        "object_id": obj.object_id,
        "name": obj.name,
        "crs": obj.crs,
        "vertical_domain": obj.vertical_domain,
        "unit": obj.unit,
        "version": obj.version,
        "provenance": J(obj.provenance.to_meta()),
    }
    if kind == "well":
        s.update(stations=J(obj.stations), representation=obj.representation,
                 z_unit=obj.z_unit, well_asset_id=obj.well_asset_id,
                 formation_tops=[list(t) for t in obj.formation_tops])
    elif kind == "horizon":
        s.update(z_grid=J(obj.z_grid), origin=list(obj.origin),
                 spacing=list(obj.spacing), grid_crs=obj.grid_crs,
                 horizon_asset_id=obj.horizon_asset_id,
                 confidence=J(obj.confidence) if obj.confidence is not None else None,
                 attributes=[[n, J(a)] for n, a in obj.attributes])
    elif kind == "fault":
        s.update(verts=J(obj.verts), faces=J(obj.faces),
                 representation=obj.representation,
                 z_extent=list(obj.z_extent) if obj.z_extent else None,
                 throw_m=obj.throw_m,
                 strike_dip=list(obj.strike_dip) if obj.strike_dip else None,
                 fault_asset_id=obj.fault_asset_id,
                 intersects_horizons=list(obj.intersects_horizons))
    elif kind == "volume":
        s.update(verts=J(obj.verts), faces=J(obj.faces),
                 top_id=obj.top_id, base_id=obj.base_id,
                 boundary=J(obj.boundary) if obj.boundary is not None else None,
                 formation=obj.formation,
                 facies=J(obj.facies) if obj.facies is not None else None,
                 properties=[[n, J(a)] for n, a in obj.properties],
                 cell_mesh=obj.cell_mesh,
                 quality=dict(obj.quality))
    elif kind == "tunnel":
        s.update(path=J(obj.path), radius=obj.radius)
    elif kind == "measure":
        s.update(measurement_kind=obj.measurement_kind, points=J(obj.points),
                 result=obj.result, extra=dict(obj.extra))
    return s


# ---------------------------------------------------------------------------
# case plumbing
# ---------------------------------------------------------------------------

CASES = []


def case(cid, fn, input_, fn_, *, fix=None):
    try:
        result = fn_()
        entry = {"id": cid, "fn": fn, "input": J(input_),
                 "expect": {"result": J(result)}}
    except Exception as exc:  # noqa: BLE001 — class names are the oracle
        entry = {"id": cid, "fn": fn, "input": J(input_),
                 "expect": {"raises": type(exc).__name__,
                            "message": str(exc)}}
    if fix:
        fix(entry)
    CASES.append(entry)


# ---------------------------------------------------------------------------
# canonical fixtures (real objects built by the real builders)
# ---------------------------------------------------------------------------

def hor_spec(object_id="horizon:h1", z=((0.0, 1.0, 2.0), (0.5, 1.5, 2.5),
                                      (1.0, 2.0, 3.0)), **kw):
    base = dict(kind="horizon", object_id=object_id, name="H1",
                crs="EPSG:32650", z_grid=[list(r) for r in z],
                origin=[100.0, 200.0], spacing=[2.0, 3.0])
    base.update(kw)
    return base


def well_spec(object_id="well:w1", **kw):
    base = dict(kind="well", object_id=object_id, name="W-1 井",
                crs="EPSG:32650",
                stations=[[0.0, 10.0, 20.0, 0.0],
                          [50.0, 10.5, 20.2, -49.0],
                          [120.0, 11.0, 20.8, -110.0]])
    base.update(kw)
    return base


def fault_spec(object_id="fault:f1", **kw):
    base = dict(kind="fault", object_id=object_id, name="F1",
                crs="EPSG:32650",
                verts=[[0, 0, 0], [1, 0, -1], [0, 1, -2], [1, 1, -3]],
                faces=[[0, 1, 2], [1, 3, 2]])
    base.update(kw)
    return base


def volume_spec(object_id="volume:v1", **kw):
    """A real volume built by the real builders (CONV-12 pipeline)."""
    top = domain.HorizonSurface(
        object_id="horizon:top", name="top", crs="EPSG:32650",
        z_grid=np.array([[0.0, 0.1, 0.0], [0.2, 0.3, 0.2], [0.0, 0.1, 0.0]]),
        origin=(0.0, 0.0), spacing=(10.0, 10.0))
    base = domain.HorizonSurface(
        object_id="horizon:base", name="base", crs="EPSG:32650",
        z_grid=np.array([[50.0, 50.1, 50.0], [50.2, 50.3, 50.2],
                         [50.0, 50.1, 50.0]]),
        origin=(0.0, 0.0), spacing=(10.0, 10.0))
    boundary = [[-1.0, -1.0], [25.0, -1.0], [25.0, 25.0], [-1.0, 25.0]]
    vol, _qc = builders.build_volume_shell(
        top, base, boundary, object_id=object_id, name="V1",
        formation="Fm")
    vol = domain.replace(vol, name="V1")
    s = spec_of(vol)
    s.update(kw)
    return s


def tunnel_spec(object_id="tunnel:t1", **kw):
    base = dict(kind="tunnel", object_id=object_id, name="T1",
                crs="EPSG:32650",
                path=[[0, 0, 0], [10, 0, -5], [20, 5, -8]], radius=3.5)
    base.update(kw)
    return base


def measure_spec(object_id="measure:m1", **kw):
    base = dict(kind="measure", object_id=object_id, name="M1",
                crs="EPSG:32650", measurement_kind="distance",
                points=[[0, 0, 0], [3, 4, 0]], result=5.0,
                extra={"note": "n"})
    base.update(kw)
    return base


def run(fn, input_):
    """Dispatch used only for exotic paths the lambdas don't cover."""
    raise AssertionError(fn)


# ---------------------------------------------------------------------------
# cases
# ---------------------------------------------------------------------------

def add_slugify():
    for cid, text, fb in [
        ("slug_basic", "Well A-1 井", "obj"),
        ("slug_unicode", "  Δfault—北  ", "obj"),
        ("slug_empty", "   ", "x9"),
        ("slug_symbols", "!!!...---", "obj"),
        ("slug_keep", "a.b_c-9", "obj"),
        ("slug_mixed", "A B/C\\D:E", "fb"),
        ("slug_non_str", 123.5, "obj"),
        ("slug_none", None, "obj"),
        ("slug_only_strip_chars", "-.-", "zz"),
    ]:
        case(cid, "slugify", {"text": text, "fallback": fb},
             lambda t=text, f=fb: domain._slugify(t, f))


def add_provenance():
    case("prov_default", "provenance_meta", {},
         lambda: domain.Provenance().to_meta())
    case("prov_full", "provenance_meta",
         {"source_kind": "catalog", "source_version_ids": ["v1", "v2"],
          "created_from": "segy", "demo": True},
         lambda: domain.Provenance(
             source_kind="catalog", source_version_ids=("v1", "v2"),
             created_from="segy", demo=True).to_meta())
    for cid, meta in [
        ("prov_from_none", None),
        ("prov_from_empty", {}),
        ("prov_from_partial", {"source_kind": "imported", "demo": 1}),
        ("prov_from_dict_ids", {"source_version_ids": {"a": 1, "b": 2}}),
        ("prov_from_scalar_id", {"source_version_ids": 7}),
    ]:
        case(cid, "provenance_from_meta", {"meta": meta},
             lambda m=meta: domain.Provenance.from_meta(m).to_meta())


def add_clean_ids():
    for cid, ids in [
        ("ids_none", None), ("ids_list", ["a", 1, None]),
        ("ids_empty", []), ("ids_scalar", 5), ("ids_str", "ab"),
        ("ids_dict", {"x": 1, "y": 2}),
    ]:
        case(cid, "clean_ids", {"ids": ids},
             lambda i=ids: list(domain._clean_ids(i)))


def add_make_object():
    specs = [
        # well — valid + every validation branch
        ("mk_well", well_spec()),
        ("mk_well_simplified", well_spec(
            representation="simplified_vertical",
            stations=[[0.0, 1.0, 2.0, 3.0], [100.0, 1.0, 2.0, 103.0]])),
        ("mk_well_zunit_tops", well_spec(
            z_unit="ft", well_asset_id="A1",
            formation_tops=[["FmA", 10.5], ["FmB", 99.0]])),
        ("mk_well_zunit_empty", well_spec(z_unit="")),
        ("mk_well_bad_oid", well_spec(object_id="w1")),
        ("mk_well_no_colon", well_spec(object_id="wellx")),
        ("mk_well_empty_oid", well_spec(object_id="")),
        ("mk_well_empty_name", well_spec(name="")),
        ("mk_well_wrong_prefix", well_spec(object_id="fault:w1")),
        ("mk_well_st_1d", well_spec(stations=[1.0, 2.0, 3.0])),
        ("mk_well_st_cols", well_spec(stations=[[1.0, 2.0, 3.0]])),
        ("mk_well_st_nan", well_spec(
            stations=[[0.0, 1.0, 2.0, 3.0], [5.0, None, 2.0, 4.0]])),
        ("mk_well_st_inf", well_spec(
            stations=[[0.0, 1.0, 2.0, 3.0], [5.0, "inf", 2.0, 4.0]])),
        ("mk_well_repr", well_spec(representation="lidar")),
        ("mk_well_md_dup", well_spec(
            stations=[[0.0, 1.0, 2.0, 3.0], [0.0, 9.0, 9.0, 9.0]])),
        ("mk_well_md_rev", well_spec(
            stations=[[10.0, 1.0, 2.0, 3.0], [5.0, 9.0, 9.0, 9.0]])),
        ("mk_well_md_dup_simplified", well_spec(
            representation="simplified_vertical",
            stations=[[0.0, 1.0, 2.0, 3.0], [0.0, 9.0, 9.0, 9.0]])),
        # horizon
        ("mk_hor", hor_spec()),
        ("mk_hor_nan", hor_spec(z_grid=[[1.0, None], [None, 2.0]])),
        ("mk_hor_1d", hor_spec(z_grid=[1.0, 2.0, 3.0])),
        ("mk_hor_inf", hor_spec(z_grid=[[1.0, "inf"], [0.0, 2.0]])),
        ("mk_hor_conf", hor_spec(confidence=[[0.1, 0.2, 0.3]] * 3)),
        ("mk_hor_conf_bad", hor_spec(confidence=[[0.1, 0.2]])),
        ("mk_hor_attr", hor_spec(attributes=[["amp", [[1, 2, 3]] * 3]])),
        ("mk_hor_attr_bad", hor_spec(attributes=[["amp", [[1, 2]]]])),
        ("mk_hor_empty", hor_spec(z_grid=[])),
        ("mk_hor_wrong_prefix", hor_spec(object_id="well:h")),
        # fault
        ("mk_fault", fault_spec()),
        ("mk_fault_full", fault_spec(
            representation="curtain_2p5d", z_extent=[-10.0, -500.0],
            trace_xy=[[0, 0], [5, 5]], throw_m=30.0, strike_dip=[45.0, 60.0],
            fault_asset_id="FA1", intersects_horizons=["horizon:h1"])),
        ("mk_fault_curtain_no_z", fault_spec(representation="curtain_2p5d")),
        ("mk_fault_repr", fault_spec(representation="planar")),
        ("mk_fault_v_shape", fault_spec(verts=[1, 2, 3])),
        ("mk_fault_v_nan", fault_spec(verts=[[0, 0, None]])),
        ("mk_fault_f_shape", fault_spec(faces=[[0, 1]])),
        ("mk_fault_f_neg", fault_spec(faces=[[0, 1, -1]])),
        ("mk_fault_f_oor", fault_spec(faces=[[0, 1, 9]])),
        ("mk_fault_f_empty_v", fault_spec(verts=[], faces=[[0, 1, 2]])),
        # volume
        ("mk_vol", volume_spec()),
        ("mk_vol_facies", volume_spec(
            facies=[0] * (len(volume_spec()["verts"])))),
        ("mk_vol_facies_bad", volume_spec(facies=[0, 1])),
        ("mk_vol_prop_bad", volume_spec(properties=[["p", [1.0]]])),
        ("mk_vol_no_boundary", volume_spec(boundary=None)),
        # tunnel
        ("mk_tunnel", tunnel_spec()),
        ("mk_tunnel_path_1d", tunnel_spec(path=[1, 2, 3])),
        ("mk_tunnel_path_nan", tunnel_spec(path=[[0, 0, None], [1, 1, 1]])),
        ("mk_tunnel_r0", tunnel_spec(radius=0.0)),
        ("mk_tunnel_rneg", tunnel_spec(radius=-2.0)),
        # measure
        ("mk_measure", measure_spec()),
        ("mk_measure_point", measure_spec(measurement_kind="point",
                                          result=None)),
        ("mk_measure_kind", measure_spec(measurement_kind="area")),
        ("mk_measure_pts", measure_spec(points=[[1, 2]])),
        ("mk_measure_nan", measure_spec(points=[[0, 0, 0], [None, 1, 1]])),
    ]
    for cid, spec in specs:
        case(cid, "make_object", spec, lambda s=spec: construct(s).meta())


def add_from_meta():
    metas = []
    for cid, spec in [
        ("fm_well", well_spec()),
        ("fm_hor", hor_spec()),
        ("fm_fault", fault_spec()),
        ("fm_vol", volume_spec()),
        ("fm_tunnel", tunnel_spec()),
        ("fm_measure", measure_spec()),
    ]:
        obj = construct(spec)
        metas.append((cid, spec["kind"], obj.meta()))
    # malformed / coercion paths
    metas += [
        ("fm_well_min", "well", {"object_id": "well:m", "name": "m"}),
        ("fm_well_int_name", "well", {"object_id": "well:m", "name": 5}),
        ("fm_well_no_oid", "well", {"name": "m"}),
        ("fm_well_no_name", "well", {"object_id": "well:m"}),
        ("fm_well_zunit", "well", {"object_id": "well:m", "name": "m",
                                   "z_unit": "ft", "version": "3"}),
        ("fm_well_tops", "well", {"object_id": "well:m", "name": "m",
                                  "formation_tops": [["A", 1.5], ["B", 2]]}),
        ("fm_hor_defaults", "horizon", {"object_id": "horizon:m",
                                        "name": "m"}),
        ("fm_fault_zext_empty", "fault",
         {"object_id": "fault:m", "name": "m", "z_extent": [],
          "strike_dip": [1.0, 2.0], "throw_m": None}),
        ("fm_vol_quality", "volume",
         {"object_id": "volume:m", "name": "m",
          "quality": {"dropped_crossed": 2, "min_thickness": 0.5},
          "top_id": "horizon:t", "base_id": "horizon:b"}),
        ("fm_measure_pts", "measure",
         {"object_id": "measure:m", "name": "m",
          "points": [[1, 2, 3]], "result": 1.5, "extra": {"k": 1}}),
        ("fm_ver_str", "tunnel",
         {"object_id": "tunnel:m", "name": "m", "version": "7",
          "radius": "4.5"}),
    ]
    for cid, kind, meta in metas:
        cls = domain.ModelAssembly._KIND_TO_CLS[kind]
        case(cid, "object_from_meta", {"kind": kind, "meta": J(meta)},
             lambda c=cls, m=meta: c.from_meta(m).meta())


def add_geometry_stats():
    for cid, spec in [
        ("gs_well", well_spec()),
        ("gs_well_empty", well_spec(stations=[])),
        ("gs_hor", hor_spec()),
        ("gs_hor_nan", hor_spec(z_grid=[[1.0, None], [None, 2.0]])),
        ("gs_hor_allnan", hor_spec(z_grid=[[None, None], [None, None]])),
        ("gs_hor_empty", hor_spec(z_grid=[])),
        ("gs_fault", fault_spec()),
        ("gs_fault_empty", fault_spec(verts=[], faces=[])),
        ("gs_vol", volume_spec()),
        ("gs_tunnel", tunnel_spec()),
        ("gs_measure", measure_spec()),
        ("gs_measure_empty", measure_spec(points=[])),
    ]:
        case(cid, "geometry_stats", spec,
             lambda s=spec: domain.geometry_stats(construct(s)))


def add_assembly():
    opsets = [
        ("asm_add_meta", [
            {"op": "add", "spec": well_spec()},
            {"op": "add", "spec": fault_spec()},
            {"op": "to_meta"},
        ]),
        ("asm_dup", [
            {"op": "add", "spec": well_spec()},
            {"op": "add", "spec": well_spec()},
        ]),
        ("asm_replace", [
            {"op": "add", "spec": well_spec()},
            {"op": "replace", "spec": well_spec(name="W2", version=2)},
            {"op": "ids"},
        ]),
        ("asm_replace_missing", [
            {"op": "replace", "spec": well_spec()},
        ]),
        ("asm_remove", [
            {"op": "add", "spec": well_spec()},
            {"op": "add", "spec": fault_spec()},
            {"op": "remove", "object_id": "well:w1"},
            {"op": "remove", "object_id": "well:nope"},
            {"op": "ids"},
        ]),
        ("asm_clear_kind", [
            {"op": "add", "spec": well_spec()},
            {"op": "add", "spec": fault_spec()},
            {"op": "clear", "kind": "well"},
            {"op": "ids"},
        ]),
        ("asm_clear_all", [
            {"op": "add", "spec": well_spec()},
            {"op": "clear"},
            {"op": "ids"},
        ]),
        ("asm_bump", [
            {"op": "add", "spec": well_spec()},
            {"op": "bump_version", "object_id": "well:w1"},
            {"op": "to_meta"},
        ]),
        ("asm_bump_missing", [
            {"op": "bump_version", "object_id": "well:nope"},
        ]),
        ("asm_objects_kind", [
            {"op": "add", "spec": well_spec()},
            {"op": "add", "spec": fault_spec()},
            {"op": "ids", "kind": "well"},
            {"op": "ids", "kind": "alien"},
        ]),
        ("asm_apply_meta", [
            {"op": "apply_meta", "meta": {
                "name": "asm2", "frame": "local",
                "display": {"well:w1": {"color": [1, 0, 0]}},
                "objects": [
                    well_spec() and construct(well_spec()).meta(),
                    {"object_id": "alien:x", "name": "x"},
                    {"object_id": "fault:f1", "name": "f",
                     "verts": "not-an-array"},
                    construct(fault_spec()).meta(),
                    {"object_id": "well:w1", "name": "dup"},
                ]}},
            {"op": "ids"},
            {"op": "to_meta"},
        ]),
        ("asm_display_removed", [
            {"op": "add", "spec": well_spec()},
            {"op": "apply_meta", "meta": {
                "display": {"well:w1": {"visible": False}}}},
            {"op": "remove", "object_id": "well:w1"},
            {"op": "to_meta"},
        ]),
    ]

    def play(ops):
        asm = domain.ModelAssembly()
        out = []
        for op in ops:
            kind = op["op"]
            try:
                if kind == "add":
                    r = asm.add(construct(op["spec"])).object_id
                elif kind == "replace":
                    r = asm.replace(construct(op["spec"])).object_id
                elif kind == "remove":
                    r = asm.remove(op["object_id"])
                elif kind == "clear":
                    r = asm.clear(op.get("kind"))
                elif kind == "bump_version":
                    r = asm.bump_version(op["object_id"]).version
                elif kind == "ids":
                    r = asm.ids(op.get("kind"))
                elif kind == "apply_meta":
                    r = asm.apply_meta(op["meta"])
                elif kind == "to_meta":
                    r = asm.to_meta()
                else:
                    raise AssertionError(kind)
                out.append({"ok": J(r)})
            except Exception as exc:  # noqa: BLE001
                out.append({"raises": type(exc).__name__,
                            "message": str(exc)})
        return out

    for cid, ops in opsets:
        case(cid, "assembly_ops", {"ops": ops}, lambda o=ops: play(o))


def add_qc():
    specs = [
        # well branches
        ("qc_well_ok", well_spec()),
        ("qc_well_no_crs", well_spec(crs="unknown")),
        ("qc_well_empty_crs", well_spec(crs="")),
        ("qc_well_no_st", well_spec(stations=[])),
        ("qc_well_2st", well_spec(
            stations=[[0, 0, 0, 0], [10, 1, 1, -9]])),
        ("qc_well_simplified", well_spec(
            representation="simplified_vertical",
            stations=[[0, 0, 0, 0], [10, 0, 0, -10]])),
        ("qc_well_mixed_units", well_spec(z_unit="ft")),
        ("qc_well_zero_seg", well_spec(
            stations=[[0, 0, 0, 0], [10, 0, 0, 0], [20, 5, 5, -9]])),
        ("qc_well_nonfinite", well_spec(
            _mutate=[{"field": "stations", "index": 5, "value": None}])),
        ("qc_well_md", well_spec(
            stations=[[0, 0, 0, 0], [5, 1, 1, -4], [5, 2, 2, -9]],
            representation="simplified_vertical")),
        # horizon branches
        ("qc_hor_ok", hor_spec()),
        ("qc_hor_empty", hor_spec(z_grid=[])),
        ("qc_hor_nan_some", hor_spec(z_grid=[[1.0, None], [None, 2.0],
                                              [3.0, 4.0, 5.0]])),
        ("qc_hor_nan_most", hor_spec(z_grid=[[1.0, None, None],
                                              [None, None, None],
                                              [None, None, 2.0]])),
        ("qc_hor_allnan", hor_spec(z_grid=[[None, None], [None, None]])),
        ("qc_hor_inf", hor_spec(
            z_grid=[[1.0, 2.0], [3.0, 4.0]],
            _mutate=[{"field": "z_grid", "index": [0, 1],
                      "value": "inf"}])),
        ("qc_hor_no_crs", hor_spec(crs="unknown", grid_crs="")),
        ("qc_hor_gridcrs", hor_spec(crs="unknown", grid_crs="ilxl")),
        ("qc_hor_no_prov", hor_spec(horizon_asset_id="")),
        ("qc_hor_asset", hor_spec(horizon_asset_id="HA1")),
        ("qc_hor_degenerate", hor_spec(
            z_grid=[[0.0, 0.0], [0.0, 0.0]],
            origin=[0.0, 0.0], spacing=[0.0, 0.0])),
        # fault branches
        ("qc_fault_ok", fault_spec()),
        ("qc_fault_no_crs", fault_spec(crs="unknown")),
        ("qc_fault_empty", fault_spec(verts=[], faces=[])),
        ("qc_fault_no_faces", fault_spec(faces=[])),
        ("qc_fault_curtain", fault_spec(
            representation="curtain_2p5d", z_extent=[0.0, -10.0])),
        ("qc_fault_degenerate", fault_spec(
            verts=[[0, 0, 0], [0, 0, 0], [1, 1, 1]],
            faces=[[0, 1, 2]])),
        ("qc_fault_nonmanifold", fault_spec(
            verts=[[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
            faces=[[0, 1, 2], [0, 1, 2], [0, 1, 3]])),
        ("qc_fault_crash", fault_spec(
            _mutate=[{"field": "faces", "index": 0, "value": 9}])),
        # volume branches
        ("qc_vol_ok", volume_spec()),
        ("qc_vol_no_crs", volume_spec(crs="unknown")),
        ("qc_vol_no_refs", volume_spec(top_id="", base_id="")),
        ("qc_vol_empty", volume_spec(verts=[], faces=[])),
        ("qc_vol_zero_thick", volume_spec(
            quality={"dropped_crossed": 0, "column_count": 9,
                     "min_thickness": 0.0})),
        ("qc_vol_crossed", volume_spec(
            quality={"dropped_crossed": 2, "column_count": 9,
                     "min_thickness": 1.0})),
        ("qc_vol_crossed_all", volume_spec(
            quality={"dropped_crossed": 9, "column_count": 9,
                     "min_thickness": 1.0})),
        ("qc_vol_no_prov", volume_spec(
            provenance={"source_kind": "derived"})),
        # tunnel / measure
        ("qc_tunnel_ok", tunnel_spec()),
        ("qc_tunnel_1pt", tunnel_spec(path=[[0, 0, 0]])),
        ("qc_tunnel_no_crs", tunnel_spec(crs="unknown")),
        ("qc_tunnel_both", tunnel_spec(crs="unknown", path=[[0, 0, 0]])),
        ("qc_measure_ok", measure_spec()),
        ("qc_measure_no_crs", measure_spec(crs="")),
        ("qc_measure_no_result", measure_spec(result=None)),
        ("qc_measure_point_none", measure_spec(
            measurement_kind="point", result=None)),
    ]
    for cid, spec in specs:
        def make(s=spec):
            return mutate(construct(s), s)
        case(cid, "qc_object", spec,
             lambda s=spec, m=make: gm_qc.qc_object(m()).to_meta())


def add_qc_assembly():
    def play(specs, known):
        asm = domain.ModelAssembly()
        for s in specs:
            asm.add(mutate(construct(s), s))
        return gm_qc.qc_assembly(
            asm, known_source_ids=known).to_meta()

    case("qca_two", "qc_assembly",
         {"objects": [well_spec(), fault_spec()], "known": None},
         lambda: play([well_spec(), fault_spec()], None))
    case("qca_stale", "qc_assembly",
         {"objects": [
             well_spec(provenance={
                 "source_kind": "catalog",
                 "source_version_ids": ["v-old", "v-gone"]}),
             fault_spec(provenance={
                 "source_kind": "catalog",
                 "source_version_ids": ["v-live"]}),
         ], "known": ["v-live"]},
         lambda: play(
             [well_spec(provenance={
                 "source_kind": "catalog",
                 "source_version_ids": ["v-old", "v-gone"]}),
              fault_spec(provenance={
                  "source_kind": "catalog",
                  "source_version_ids": ["v-live"]})],
             ["v-live"]))
    case("qca_stale_partial", "qc_assembly",
         {"objects": [
             well_spec(provenance={
                 "source_kind": "catalog",
                 "source_version_ids": ["v-old", "v-live"]}),
         ], "known": ["v-live"]},
         lambda: play(
             [well_spec(provenance={
                 "source_kind": "catalog",
                 "source_version_ids": ["v-old", "v-live"]})],
             ["v-live"]))
    case("qca_empty_known", "qc_assembly",
         {"objects": [well_spec(provenance={
             "source_kind": "catalog",
             "source_version_ids": ["v1"]})], "known": []},
         lambda: play(
             [well_spec(provenance={
                 "source_kind": "catalog",
                 "source_version_ids": ["v1"]})], []))


def add_assert_exportable():
    def play(specs, report=None):
        objs = [mutate(construct(s), s) for s in specs]
        return gm_qc.assert_exportable(objs, report).to_meta()

    case("ae_pass", "assert_exportable",
         {"objects": [well_spec(), fault_spec()]},
         lambda: play([well_spec(), fault_spec()]))
    # objects construct fine but QC-block (missing CRS / <2 path points):
    # exercises the QCBlockerError message (sorted ids + issue lines).
    case("ae_block", "assert_exportable",
         {"objects": [well_spec(crs="unknown"),
                      tunnel_spec(path=[[0, 0, 0]])]},
         lambda: play([well_spec(crs="unknown"),
                       tunnel_spec(path=[[0, 0, 0]])]))
    # supplied report: no recompute (an empty report lets a blocker through)
    case("ae_supplied_report", "assert_exportable",
         {"objects": [well_spec(crs="unknown")], "report": "empty"},
         lambda: play([well_spec(crs="unknown")], gm_qc.QCReport()))


def add_exporters(tmp: Path):
    vol = volume_spec()
    top_g = dict(kind="horizon", object_id="horizon:top", name="top",
                 crs="EPSG:32650",
                 z_grid=[[0.0, 0.1, 0.0], [0.2, 0.3, 0.2], [0.0, 0.1, 0.0]],
                 origin=[0.0, 0.0], spacing=[10.0, 10.0])
    base_g = dict(kind="horizon", object_id="horizon:base", name="base",
                  crs="EPSG:32650",
                  z_grid=[[50.0, 50.1, 50.0], [50.2, 50.3, 50.2],
                          [50.0, 50.1, 50.0]],
                  origin=[0.0, 0.0], spacing=[10.0, 10.0])

    def horizons(t, b):
        def to_surf(s):
            return domain.HorizonSurface(
                object_id=s["object_id"], name=s["name"], crs=s["crs"],
                z_grid=arr(s["z_grid"]), origin=tuple(s["origin"]),
                spacing=tuple(s["spacing"]))
        return to_surf(t), to_surf(b)

    ex_cases = [
        ("ex_flac", "flac3d", vol, "v1.f3grid",
         dict(top=None, base=None, n_layers=4, zone_name="GEOMODEL"),
         {"top_spec": top_g, "base_spec": base_g}),
        ("ex_flac_regrid", "flac3d", vol, "v2.f3grid", {}, None),
        ("ex_flac_layers", "flac3d", vol, "v3.f3grid",
         dict(top=None, base=None, n_layers=2, zone_name="Z9"),
         {"top_spec": top_g, "base_spec": base_g}),
        ("ex_flac_no_bnd", "flac3d", volume_spec(boundary=None),
         "v4.f3grid", {}, None),
        ("ex_flac_blocker", "flac3d", volume_spec(crs="unknown"),
         "v5.f3grid", {}, None),
        ("ex_abaqus", "abaqus", vol, "v1.inp",
         dict(top=None, base=None, n_layers=4, part_name="GEOMODEL"),
         {"top_spec": top_g, "base_spec": base_g}),
        ("ex_abaqus_regrid", "abaqus", vol, "v2.inp", {}, None),
        ("ex_abaqus_no_bnd", "abaqus", volume_spec(boundary=None),
         "v3.inp", {}, None),
        ("ex_obj_vol", "obj", vol, "v1.obj", {}, None),
        ("ex_obj_fault", "obj", fault_spec(), "f1.obj",
         dict(label="LBL"), None),
        ("ex_obj_well", "obj", well_spec(), "w1.obj", {}, None),
        ("ex_obj_empty", "obj", fault_spec(faces=[]), "f2.obj", {}, None),
        ("ex_stl", "stl", fault_spec(), "f1.stl", {}, None),
        ("ex_stl_degenerate", "stl", fault_spec(
            verts=[[0, 0, 0], [0, 0, 0], [1, 1, 1]], faces=[[0, 1, 2]]),
         "f2.stl", {}, None),
        ("ex_vtp", "vtp", fault_spec(), "f1.vtp", {}, None),
        ("ex_vtp_pdata", "vtp", fault_spec(),
         "f2.vtp", dict(point_data={"facies": [1.0, 2, 3, 4],
                                    "conf": [0.1, 0.2, 0.3, 0.4]}), None),
        ("ex_vtp_pdata_bad", "vtp", fault_spec(),
         "f3.vtp", dict(point_data={"bad": [1.0]}), None),
        ("ex_vtp_vol", "vtp", vol, "v1.vtp", {}, None),
    ]
    for cid, fn, spec, fname, kw, grids in ex_cases:
        def go(fn=fn, spec=spec, fname=fname, kw=dict(kw), grids=grids):
            obj = mutate(construct(spec), spec)
            kwargs = dict(kw)
            if grids:
                t, b = horizons(grids["top_spec"], grids["base_spec"])
                kwargs["top"], kwargs["base"] = t, b
            fmap = {"flac3d": exporters.export_volume_flac3d,
                    "abaqus": exporters.export_volume_abaqus,
                    "obj": exporters.export_mesh_obj,
                    "stl": exporters.export_mesh_stl,
                    "vtp": exporters.export_mesh_vtp}
            p = fmap[fn](obj, tmp / fname, **kwargs)
            sidecar = p.with_name(p.stem + ".provenance.json")
            return {"file": (p.read_bytes() if fn == "stl"
                             else p.read_text(encoding="utf-8")),
                    "sidecar_name": sidecar.name,
                    "sidecar": json.loads(sidecar.read_text("utf-8"))}
        inp = {"spec": spec, "name": fname, **kw}
        if grids:
            inp["top_spec"], inp["base_spec"] = grids["top_spec"], grids["base_spec"]
        case(cid, "export_" + fn, inp, go)


def add_readers(tmp: Path):
    # Generate real files with the real writers, then freeze reader output
    # on both the real files and hand-mangled variants.
    vol = construct(volume_spec())
    top = domain.HorizonSurface(
        object_id="horizon:t", name="t", crs="EPSG:32650",
        z_grid=arr([[0.0, 0.1, 0.0], [0.2, 0.3, 0.2], [0.0, 0.1, 0.0]]),
        origin=(0.0, 0.0), spacing=(10.0, 10.0))
    base = domain.HorizonSurface(
        object_id="horizon:b", name="b", crs="EPSG:32650",
        z_grid=arr([[50.0, 50.1, 50.0], [50.2, 50.3, 50.2],
                    [50.0, 50.1, 50.0]]),
        origin=(0.0, 0.0), spacing=(10.0, 10.0))
    p_f3 = exporters.export_volume_flac3d(vol, tmp / "r.f3grid",
                                          top=top, base=base)
    p_inp = exporters.export_volume_abaqus(vol, tmp / "r.inp",
                                           top=top, base=base)
    fault = construct(fault_spec())
    p_obj = exporters.export_mesh_obj(fault, tmp / "r.obj")
    p_stl = exporters.export_mesh_stl(fault, tmp / "r.stl")
    p_vtp = exporters.export_mesh_vtp(
        fault, tmp / "r.vtp", point_data={"facies": [1.0, 2, 3, 4]})

    f3 = p_f3.read_text()
    inp = p_inp.read_text()
    obj_t = p_obj.read_text()
    stl_b = p_stl.read_bytes()
    vtp_t = p_vtp.read_text()

    rd = [
        ("rd_f3", "read_flac3d_grid", f3),
        ("rd_f3_empty", "read_flac3d_grid", "* nothing\n"),
        ("rd_f3_no_z", "read_flac3d_grid", "G 1 0 0 0\n"),
        ("rd_f3_bad_ref", "read_flac3d_grid",
         "G 1 0 0 0\nZ B8 1 1 1 1 1 2 2 2 2\n"),
        ("rd_f3_junk", "read_flac3d_grid",
         "junk line\nG 1 0 0 0\nZ B8 1 1 1 1 1 1 1 1 1\n"),
        ("rd_inp", "read_abaqus_inp", inp),
        ("rd_inp_no_elem", "read_abaqus_inp", "*NODE\n1, 0, 0, 0\n"),
        ("rd_inp_bad_type", "read_abaqus_inp",
         "*NODE\n1, 0, 0, 0\n*ELEMENT, TYPE=C3D4\n1, 1, 1, 1, 1\n"),
        ("rd_inp_bad_ref", "read_abaqus_inp",
         "*NODE\n1, 0, 0, 0\n*ELEMENT, TYPE=C3D8\n1, 1, 1, 1, 1, 1, 1, 1, 9\n"),
        ("rd_obj", "read_obj", obj_t),
        ("rd_obj_empty", "read_obj", "# nothing\n"),
        ("rd_obj_slash", "read_obj", "v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1/1/1 2/2 3\n"),
        ("rd_obj_bad_ref", "read_obj", "v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 9\n"),
        ("rd_vtp", "read_vtp", vtp_t),
        ("rd_vtp_malformed", "read_vtp", "<VTKFile"),
        ("rd_vtp_not_vtk", "read_vtp", "<foo/>"),
        ("rd_vtp_not_poly", "read_vtp",
         '<VTKFile type="ImageData"></VTKFile>'),
        ("rd_vtp_no_piece", "read_vtp",
         '<VTKFile type="PolyData"></VTKFile>'),
        ("rd_vtp_no_conn", "read_vtp",
         '<VTKFile type="PolyData"><PolyData>'
         '<Piece NumberOfPoints="3" NumberOfPolys="1">'
         "<Polys></Polys></Piece></PolyData></VTKFile>"),
        ("rd_vtp_no_pts", "read_vtp",
         '<VTKFile type="PolyData"><PolyData>'
         '<Piece NumberOfPoints="3" NumberOfPolys="1">'
         "<Polys><DataArray Name=\"connectivity\">0 1 2</DataArray></Polys>"
         "</Piece></PolyData></VTKFile>"),
        ("rd_vtp_count_mismatch", "read_vtp",
         '<VTKFile type="PolyData"><PolyData>'
         '<Piece NumberOfPoints="9" NumberOfPolys="1">'
         "<Points><DataArray Name=\"Points\">0 0 0 1 0 0 0 1 0</DataArray>"
         "</Points><Polys>"
         "<DataArray Name=\"connectivity\">0 1 2</DataArray></Polys>"
         "</Piece></PolyData></VTKFile>"),
        ("rd_vtp_conn_oor", "read_vtp",
         '<VTKFile type="PolyData"><PolyData>'
         '<Piece NumberOfPoints="3" NumberOfPolys="1">'
         "<Points><DataArray Name=\"Points\">0 0 0 1 0 0 0 1 0</DataArray>"
         "</Points><Polys>"
         "<DataArray Name=\"connectivity\">0 1 9</DataArray></Polys>"
         "</Piece></PolyData></VTKFile>"),
    ]
    suffixes = {"read_flac3d_grid": ".f3grid", "read_abaqus_inp": ".inp",
                "read_obj": ".obj", "read_stl": ".stl",
                "read_vtp": ".vtp"}
    for cid, fn, text in rd:
        case(cid, fn,
             {"name": "$FX/case" + suffixes[fn], "text": text},
             lambda f=fn, t=text: _read(f, tmp, t), fix=fx_fix)

    for cid, payload in [("rd_stl", stl_b), ("rd_stl_trunc", stl_b[:60]),
                         ("rd_stl_size", stl_b + b"x")]:
        case(cid, "read_stl", {"name": "$FX/case.stl", "b64": payload},
             lambda p=payload: _read("read_stl", tmp, p), fix=fx_fix)


def _read(fn, tmp, payload):
    suffix = {"read_flac3d_grid": ".f3grid", "read_abaqus_inp": ".inp",
              "read_obj": ".obj", "read_stl": ".stl",
              "read_vtp": ".vtp"}[fn]
    p = tmp / ("case" + suffix)
    if isinstance(payload, (bytes, bytearray)):
        p.write_bytes(payload)
    else:
        p.write_text(payload, encoding="utf-8")
    fmap = {"read_flac3d_grid": exporters.read_flac3d_grid,
            "read_abaqus_inp": exporters.read_abaqus_inp,
            "read_obj": exporters.read_obj,
            "read_stl": exporters.read_stl,
            "read_vtp": exporters.read_vtp}
    out = fmap[fn](p)
    # zones/elements are tuples of ints — J() handles; nodes arrays too.
    return out


def add_validate_export(tmp: Path):
    vol = construct(volume_spec())
    top = domain.HorizonSurface(
        object_id="horizon:t", name="t", crs="EPSG:32650",
        z_grid=arr([[0.0, 0.1, 0.0], [0.2, 0.3, 0.2], [0.0, 0.1, 0.0]]),
        origin=(0.0, 0.0), spacing=(10.0, 10.0))
    base = domain.HorizonSurface(
        object_id="horizon:b", name="b", crs="EPSG:32650",
        z_grid=arr([[50.0, 50.1, 50.0], [50.2, 50.3, 50.2],
                    [50.0, 50.1, 50.0]]),
        origin=(0.0, 0.0), spacing=(10.0, 10.0))
    p_f3 = exporters.export_volume_flac3d(vol, tmp / "v.f3grid",
                                          top=top, base=base)
    fault = construct(fault_spec())
    p_obj = exporters.export_mesh_obj(fault, tmp / "v.obj")
    p_stl = exporters.export_mesh_stl(fault, tmp / "v.stl")
    p_vtp = exporters.export_mesh_vtp(fault, tmp / "v.vtp")

    def play(name, payload, spec):
        p = tmp / name
        if isinstance(payload, (bytes, bytearray)):
            p.write_bytes(payload)
        else:
            p.write_text(payload, encoding="utf-8")
        return exporters.validate_export(p, construct(spec))

    vol_spec = spec_of(vol)
    fault_spec_j = spec_of(fault)
    cases = [
        ("ve_f3", "v.f3grid", p_f3.read_text(), vol_spec),
        ("ve_inp_missing", "v.inp", "", vol_spec),  # file exists? write ""
        ("ve_obj", "v.obj", p_obj.read_text(), fault_spec_j),
        ("ve_obj_faces", "v.obj",
         p_obj.read_text() + "f 1 1 1\n", fault_spec_j),
        ("ve_obj_bounds", "v.obj",
         "v 100 100 100\nv 1 0 0\nv 0 1 0\nv 0 0 1\nf 1 2 3\nf 1 2 4\n",
         fault_spec_j),
        ("ve_stl", "v.stl", p_stl.read_bytes(), fault_spec_j),
        ("ve_stl_count", "v.stl",
         p_stl.read_bytes()[:80] + b"\x02\x00\x00\x00" + p_stl.read_bytes()[84:],
         fault_spec_j),
        ("ve_vtp", "v.vtp", p_vtp.read_text(), fault_spec_j),
        ("ve_vtp_bounds", "v.vtp", p_vtp.read_text().replace(
            "0.000000", "9.000000", 1), fault_spec_j),
        ("ve_unknown", "v.xyz", "x", fault_spec_j),
        ("ve_upper_suffix", "v.OBJ", p_obj.read_text(), fault_spec_j),
    ]
    for cid, name, payload, spec in cases:
        case(cid, "validate_export",
             {"name": "$FX/" + name, "file": J(payload), "spec": spec},
             lambda n=name, p=payload, s=spec: play(n, p, s), fix=fx_fix)


def add_structured_grid(tmp: Path):
    for cid, spec in [
        ("sg_default", {}),
        ("sg_small", {"nx": 2, "ny": 3, "nz": 1}),
        ("sg_zero_x", {"nx": 0, "ny": 2, "nz": 2}),
        ("sg_zero_y", {"nx": 2, "ny": 0, "nz": 2}),
        ("sg_spacing", {"nx": 1, "ny": 1, "nz": 1,
                        "dx": 2.5, "dy": 0.5, "dz": 3.0}),
    ]:
        kw = {"nx": 10, "ny": 10, "nz": 10, "dx": 10.0, "dy": 10.0,
              "dz": 10.0}
        kw.update(spec)

        def go(k=kw):
            nodes, elements = exporters._generate_structured_grid(
                exporters.GridSpec(**{kk: k[kk] for kk in
                                      ("nx", "ny", "nz", "dx", "dy", "dz")}))
            return {"nodes": nodes, "elements": elements}
        case(cid, "structured_grid", kw, go)

    def legacy(fn, name, kw):
        p = tmp / name
        r = fn(str(p), **kw)
        return {"result": r, "file": p.read_text(encoding="utf-8")}

    case("lg_flac", "export_to_flac3d",
         {"nx": 2, "ny": 2, "nz": 1, "dx": 5.0, "dy": 5.0, "dz": 2.0},
         lambda: legacy(exporters.export_to_flac3d, "lg.f3grid",
                        {"nx": 2, "ny": 2, "nz": 1,
                         "dx": 5.0, "dy": 5.0, "dz": 2.0}))
    case("lg_abaqus", "export_to_abaqus",
         {"nx": 2, "ny": 2, "nz": 1, "dx": 5.0, "dy": 5.0, "dz": 2.0},
         lambda: legacy(exporters.export_to_abaqus, "lg.inp",
                        {"nx": 2, "ny": 2, "nz": 1,
                         "dx": 5.0, "dy": 5.0, "dz": 2.0}))


def add_advisor():
    bh_cases = [
        ("adv_bh_clean", [{"name": "W1", "x": 0, "y": 0, "total_depth": 100,
                           "layers": [{"top": 0, "bottom": 50,
                                       "lithology": "砂岩"},
                                      {"top": 50, "bottom": 100,
                                       "lithology": "泥岩"}]}]),
        ("adv_bh_dict", [{"name": "W1"}]),  # all defaults
        ("adv_bh_bad_xy", [{"name": "W1", "x": None, "y": 0,
                            "total_depth": 10, "layers": []}]),
        ("adv_bh_neg_td", [{"name": "W1", "x": 0, "y": 0,
                            "total_depth": -5, "layers": []}]),
        ("adv_bh_inverted", [{"name": "W1", "x": 0, "y": 0,
                              "total_depth": 100,
                              "layers": [{"top": 60, "bottom": 50,
                                          "lithology": "L1"}]}]),
        ("adv_bh_overlap", [{"name": "W1", "x": 0, "y": 0,
                             "total_depth": 100,
                             "layers": [{"top": 0, "bottom": 60,
                                         "lithology": "L1"},
                                        {"top": 55, "bottom": 90,
                                         "lithology": "L2"}]}]),
        ("adv_bh_exceed", [{"name": "W1", "x": 0, "y": 0,
                            "total_depth": 50,
                            "layers": [{"top": 0, "bottom": 80,
                                        "lithology": "L1"}]}]),
        ("adv_bh_multi", [{"name": "A", "x": 0, "y": 0, "total_depth": 10,
                           "layers": []},
                          {"name": "B", "x": 0, "y": 0, "total_depth": -1,
                           "layers": [{"top": 5, "bottom": 2,
                                       "lithology": "L"}]}]),
        ("adv_bh_bad_type", [42]),
        ("adv_bh_empty", []),
    ]
    for cid, records in bh_cases:
        case(cid, "check_boreholes", {"records": records},
             lambda r=records: advisor.check_boreholes(r))

    ft_cases = [
        ("adv_ft_clean", [{"name": "F1", "normal": [1, 0, 0], "d": 0},
                          {"name": "F2", "normal": [0, 1, 0], "d": 0}]),
        ("adv_ft_coplanar", [{"name": "F1", "normal": [1, 0, 0], "d": 0},
                             {"name": "F2", "normal": [-1, 0, 0], "d": -5}]),
        ("adv_ft_far", [{"name": "F1", "normal": [1, 0, 0], "d": 0},
                        {"name": "F2", "normal": [1, 0, 0], "d": 100}]),
        ("adv_ft_scaled", [{"name": "F1", "normal": [2, 0, 0], "d": 10},
                           {"name": "F2", "normal": [1, 0, 0], "d": 6}]),
        ("adv_ft_near_angle", [{"name": "F1", "normal": [1, 0, 0], "d": 0},
                               {"name": "F2", "normal": [0.999, 0.044, 0],
                                "d": 1}]),
        ("adv_ft_zero_normal", [{"name": "F1", "normal": [0, 0, 0], "d": 0},
                                {"name": "F2", "normal": [1, 0, 0], "d": 0}]),
        ("adv_ft_dict", [{"name": "F1"}]),
        ("adv_ft_bad_type", ["x"]),
        ("adv_ft_empty", []),
    ]
    for cid, records in ft_cases:
        case(cid, "check_coplanar_faults", {"records": records},
             lambda r=records: advisor.check_coplanar_faults(r))


def add_lithology():
    layers = [
        {"top": 0, "bottom": 10, "lithology": "砂岩"},
        {"top": 10, "bottom": 20, "lithology": "泥岩"},
        {"top": 15, "bottom": 25, "lithology": "未知岩"},
    ]
    depths = [0.0, 5.0, 10.0, 14.9, 15.0, 20.0, 24.9, 25.0, 30.0]
    for cid, table, default in [
        ("lith_gr", "LITHO_GR", 60.0),
        ("lith_sonic", "LITHO_SONIC", 180.0),
        ("lith_density", "LITHO_DENSITY", 2.4),
        ("lith_ai", "LITHO_AI", 6000.0),
    ]:
        t = getattr(lithology, table)
        case(cid, "sample_log_values",
             {"layers": layers, "depths": depths, "table": table,
              "default": default},
             lambda t=t, d=default: lithology.sample_log_values(
                 layers, np.asarray(depths, dtype=np.float32), t, d))
    case("lith_empty_layers", "sample_log_values",
         {"layers": [], "depths": depths, "table": "LITHO_GR",
          "default": 60.0},
         lambda: lithology.sample_log_values(
             [], np.asarray(depths, dtype=np.float32),
             lithology.LITHO_GR, 60.0))
    case("lith_tables", "lithology_tables", {},
         lambda: {"LITHO_GR": lithology.LITHO_GR,
                  "LITHO_SONIC": lithology.LITHO_SONIC,
                  "LITHO_DENSITY": lithology.LITHO_DENSITY,
                  "LITHO_AI": lithology.LITHO_AI,
                  "DEFAULT_GR": lithology.DEFAULT_GR,
                  "DEFAULT_SONIC": lithology.DEFAULT_SONIC,
                  "DEFAULT_DENSITY": lithology.DEFAULT_DENSITY,
                  "DEFAULT_AI": lithology.DEFAULT_AI})


def add_builders():
    cases = [
        ("bw_traj", "build_well_trajectory",
         {"name": "Well A", "stations": [[0, 1, 2, 3], [5, 4, 5, 6]],
          "crs": "EPSG:32650"}),
        ("bw_traj_defaults", "build_well_trajectory",
         {"name": "W", "stations": [[0, 1, 2, 3]]}),
        ("bw_traj_shape", "build_well_trajectory",
         {"name": "W", "stations": [[0, 1, 2]]}),
        ("bw_traj_md", "build_well_trajectory",
         {"name": "W", "stations": [[5, 1, 2, 3], [5, 4, 5, 6]]}),
        ("bw_traj_oid", "build_well_trajectory",
         {"name": "W", "stations": [[0, 1, 2, 3]],
          "object_id": "well:custom"}),
        ("bw_vert_depth", "build_simplified_vertical_well",
         {"name": "W1", "head_xyz": [10.0, 20.0, 5.0],
          "total_depth": 100.0, "crs": "EPSG:32650"}),
        ("bw_vert_tvdss", "build_simplified_vertical_well",
         {"name": "W1", "head_xyz": [10.0, 20.0, 5.0],
          "total_depth": 100.0, "vertical_domain": "tvdss"}),
        ("bw_vert_twt", "build_simplified_vertical_well",
         {"name": "W1", "head_xyz": [10.0, 20.0, 0.0],
          "total_depth": 2.5, "vertical_domain": "twt"}),
        ("bw_vert_head", "build_simplified_vertical_well",
         {"name": "W1", "head_xyz": [1.0, 2.0], "total_depth": 10.0}),
        ("bw_vert_nan", "build_simplified_vertical_well",
         {"name": "W1", "head_xyz": [1.0, 2.0, None],
          "total_depth": 10.0}),
        ("bw_vert_td", "build_simplified_vertical_well",
         {"name": "W1", "head_xyz": [1.0, 2.0, 3.0],
          "total_depth": -5.0}),
        ("bf_mesh", "build_fault_from_mesh",
         {"name": "F", "verts": [[0, 0, 0], [1, 0, 0], [0, 1, 0]],
          "faces": [[0, 1, 2]], "crs": "EPSG:32650",
          "throw_m": 12.5, "strike_dip": [30.0, 60.0]}),
        ("bf_mesh_v", "build_fault_from_mesh",
         {"name": "F", "verts": [[0, 0]], "faces": []}),
        ("bf_mesh_f", "build_fault_from_mesh",
         {"name": "F", "verts": [[0, 0, 0]], "faces": [[0, 1]]}),
    ]

    def go(fn, kw):
        k = dict(kw)
        fmap = {"build_well_trajectory": builders.build_well_trajectory,
                "build_simplified_vertical_well":
                    builders.build_simplified_vertical_well,
                "build_fault_from_mesh": builders.build_fault_from_mesh}
        if fn == "build_well_trajectory":
            k["stations"] = arr(k["stations"])
            k["formation_tops"] = tuple(
                tuple(t) for t in k.get("formation_tops", ()))
        elif fn == "build_fault_from_mesh":
            k["verts"] = arr(k["verts"])
            k["faces"] = iarr(k["faces"])
        return fmap[fn](**k).meta()

    for cid, fn, kw in cases:
        case(cid, fn, kw, lambda f=fn, k=kw: go(f, k))


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    global TMP_DIR
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        TMP_DIR = tmp
        add_slugify()
        add_provenance()
        add_clean_ids()
        add_make_object()
        add_from_meta()
        add_geometry_stats()
        add_assembly()
        add_qc()
        add_qc_assembly()
        add_assert_exportable()
        add_exporters(tmp)
        add_readers(tmp)
        add_validate_export(tmp)
        add_structured_grid(tmp)
        add_advisor()
        add_lithology()
        add_builders()

    n_lower = write_lower_map()
    ids = [c["id"] for c in CASES]
    assert len(ids) == len(set(ids)), "duplicate case ids"
    doc = {"cases": CASES}
    text = json.dumps(doc, indent=1, ensure_ascii=False) + "\n"
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(CASES)} cases, {n_lower} lower-map entries, "
          f"{len(text)} bytes)")


if __name__ == "__main__":
    main()
