#pragma once

// pwb::seismic_attributes — seismic attribute kernels ported from the
// geoviz oracle (geo-viz-engine@08851951, geoviz_seismic.attributes) onto
// the frozen pwb::science algorithm SDK. Qt-free, Python-free, QGIS-free.
//
// Ten production kernels (the full paleo_workbench KERNELS table minus c3,
// which lives in libs/algorithms as seismic.coherence_c3):
//   single-trace (E line):
//     seismic.envelope / instantaneous_phase / instantaneous_frequency /
//     rms_amplitude
//   volume-structural (S line):
//     seismic.sweetness / relative_impedance / dip_il / dip_xl /
//     dip_azimuth / curvature_mean
//
// Numerical contracts (axis, units, edge handling, NaN propagation) are
// frozen in docs/development/cpp-seismic-attributes/v3-contracts.md and
// docs/development/cpp-seismic-native-stack/v3-contracts.md; the Python
// oracle is the parity reference and its fixtures are generated by
// tests/cpp/seismic_attributes/oracle/*.py with a pinned interpreter.
// Kernels compute in float64 internally where the oracle does (Hilbert
// chains) and replicate the oracle's float32 numpy chains where it does
// (gradients/cumsum); all outputs are float32.

#include <memory>
#include <string>
#include <vector>

#include <pwb/science/algorithm.hpp>
#include <pwb/science/registry.hpp>

namespace pwb::seismic_attributes {

// Factories. Each descriptor declares exactly one volume_f32 input ("volume")
// and one volume_f32 output; the output shape/strides mirror the input's
// packed layout. `build_identity` is copied into descriptors and provenance.
[[nodiscard]] std::unique_ptr<science::IAlgorithm> make_envelope(
    std::string build_identity);
[[nodiscard]] std::unique_ptr<science::IAlgorithm> make_instantaneous_phase(
    std::string build_identity);
[[nodiscard]] std::unique_ptr<science::IAlgorithm> make_instantaneous_frequency(
    std::string build_identity);
[[nodiscard]] std::unique_ptr<science::IAlgorithm> make_rms_amplitude(
    std::string build_identity);

// S-line factories (see docs/development/cpp-seismic-native-stack/
// v3-contracts.md §2 for the frozen semantics and parameter table).
[[nodiscard]] std::unique_ptr<science::IAlgorithm> make_sweetness(
    std::string build_identity);
[[nodiscard]] std::unique_ptr<science::IAlgorithm> make_relative_impedance(
    std::string build_identity);
[[nodiscard]] std::unique_ptr<science::IAlgorithm> make_dip_inline(
    std::string build_identity);
[[nodiscard]] std::unique_ptr<science::IAlgorithm> make_dip_crossline(
    std::string build_identity);
[[nodiscard]] std::unique_ptr<science::IAlgorithm> make_dip_azimuth(
    std::string build_identity);
[[nodiscard]] std::unique_ptr<science::IAlgorithm> make_curvature_mean(
    std::string build_identity);

// Explicit registration into an existing registry (the host — A line — calls
// this; no static auto-registration into shared registry.cpp). Registers the
// ten algorithms in the fixed order envelope, instantaneous_phase,
// instantaneous_frequency, rms_amplitude, sweetness, relative_impedance,
// dip_il, dip_xl, dip_azimuth, curvature_mean. A duplicate algorithm_id (any
// version, including "seismic.coherence_c3" from another module) is rejected
// by the registry: registration of that entry and all later entries is
// skipped and `rejection` carries the registry's reason ("duplicate id: …").
// `registered_ids` lists exactly what was accepted (size 10 on success).
struct RegistrationReport {
    std::vector<std::string> registered_ids;
    std::string rejection; // "" when all ten were accepted
};

[[nodiscard]] RegistrationReport register_seismic_attributes(
    science::AlgorithmRegistry& registry, std::string build_identity);

} // namespace pwb::seismic_attributes
