#pragma once

// pwb::seismic_attributes — four single-trace seismic attributes (envelope,
// instantaneous phase, instantaneous frequency, windowed RMS amplitude)
// ported from geoviz_seismic.attributes (geo-viz-engine@08851951) onto the
// frozen pwb::science algorithm SDK. Qt-free, Python-free, QGIS-free.
//
// Numerical contracts (axis, units, edge handling, NaN propagation) are
// frozen in docs/development/cpp-seismic-attributes/v3-contracts.md; the
// Python oracle is the parity reference and its fixtures are generated by
// tests/cpp/seismic_attributes/oracle/generate_attribute_fixtures.py with a
// pinned interpreter. Implementation computes in float64 internally and
// emits float32 outputs, matching the oracle's float32 output dtype.

#include <memory>
#include <string>
#include <vector>

#include <pwb/science/algorithm.hpp>
#include <pwb/science/registry.hpp>

namespace pwb::seismic_attributes {

// Algorithm ids (distinct from C3's "seismic.coherence_c3"):
//   seismic.attribute.envelope
//   seismic.attribute.instantaneous_phase
//   seismic.attribute.instantaneous_frequency
//   seismic.attribute.rms_amplitude

// Factories. Each descriptor declares exactly one volume_f32 input ("volume")
// and one volume_f32 output; the output shape/strides mirror the input's
// packed layout. `build_identity` is copied into descriptors and provenance.
[[nodiscard]] std::unique_ptr<science::IAlgorithm> make_envelope(
    std::string build_identity);
[[nodiscard]] std::unique_ptr<science::IAlgorithm> make_instantaneous_phase(
    std::string build_identity);
[[nodiscard]] std::unique_ptr<science::IAlgorithm> make_instantaneous_frequency(
    std::string build_identity);
[[nodiscard]] std::unique_ptr<science::IAlgorithm> make_rms_amplitude(
    std::string build_identity);

// Explicit registration into an existing registry (the host — A line — calls
// this; no static auto-registration into shared registry.cpp). Registers the
// four algorithms in the fixed order envelope, instantaneous_phase,
// instantaneous_frequency, rms_amplitude. A duplicate algorithm_id (any
// version, including "seismic.coherence_c3" from another module) is rejected
// by the registry: registration of that entry and all later entries is
// skipped and `rejection` carries the registry's reason ("duplicate id: …").
// `registered_ids` lists exactly what was accepted (size 4 on success).
struct RegistrationReport {
    std::vector<std::string> registered_ids;
    std::string rejection; // "" when all four were accepted
};

[[nodiscard]] RegistrationReport register_seismic_attributes(
    science::AlgorithmRegistry& registry, std::string build_identity);

} // namespace pwb::seismic_attributes
