#pragma once

// pwb::mapping::constrained_idw — faithful C++ port of the vendored Haiyou
// constrained-IDW surface kernel, i.e. the surface (grid) path of
//   paleo_workbench/_vendored/haiyou_constrained_idw/drawing/single_factor/
//     constrained_engine.py :: generate_constrained_idw
// plus its direct helpers in fast_grid.py / masks.py / direction_corridor.py
// (full-conversion plan M6, fourth engine; the Python adapter
// paleo_workbench/workflow/constrained_idw_adapter.py is the only host).
//
// Numerical behavior is frozen against the Python oracle committed at
// mapping_kernel_tests/fixtures/constrained_idw_oracle.json, generated by
// tools/oracle/generate_constrained_idw_fixtures.py: the generator spies on
// the real engine call inside run_constrained_idw and freezes the EXACT
// engine inputs (wells / boundaries / barriers / directions / config) next to
// the returned grid, so nothing is hand-derived.
//
// SCOPE (honest skips, decisions D1–D3 in
// docs/development/cpp-conversion-swarm-20/ledgers/05-decisions.md):
//   * Contour extraction / post-processing (masked_marching_squares, ring
//     closure, crossing repair, barrier trimming...) is NOT ported: it runs
//     after the returned grid is final and only writes result.contours /
//     surface_*. The engine itself verifies extract_contours=True/False
//     produce a bit-identical grid (asserted by the oracle pair
//     barrier_fault_thickness / engine_surface_only).
//   * Host glue stays Python: shapely convex-hull+buffer domain synthesis
//     (GEOS), pyproj CRS barrier-buffer heuristic, spatial-4-fold CV R^2 and
//     anchored-fidelity metrics, well/dedup/constraint mapping. The C++
//     engine consumes the resolved ring/config directly.
//   * scipy.ndimage.distance_transform_edt is ported as an EXACT Euclidean
//     distance transform (Felzenszwalb two-pass, integer squared distances +
//     IEEE sqrt -> bit-identical values). An all-foreground input has no
//     background and is reported as infinity; scipy's value there is
//     undefined (uninitialized feature indices) and the state is unreachable
//     from the frozen pipeline.
//   * estimate_mean_well_spacing subsamples 400 wells through
//     numpy PCG64 for n>400 — not reproducible cross-language; the port
//     computes over all wells instead (all oracle fixtures have n<=400).
//
// Provenance (vendored ATTRIBUTION.md, kept per its license terms):
// upstream WWX9/haiyou-visualization @ 5b8f8f9855d541e2f5886f5b321afdcf70c08a51,
// selectively vendored; host fixes preserved here: barrier corridor stays
// nodata (#370), per-cell line-of-sight whenever barriers exist (#382),
// gap-fill hull existence on the limit-to-coverage path (#924).
// Qt-free, Python-free, numpy-free, scipy-free.

#include <pwb/mapping/contouring.hpp>

#include <map>
#include <optional>
#include <string>
#include <vector>

namespace pwb::mapping::constrained_idw {

struct Well {
    std::string well_id;
    double x = 0.0;
    double y = 0.0;
    double value = 0.0;
    bool is_control_point = false;
};

struct BoundaryPolygon {
    std::vector<Point> exterior;
    std::vector<std::vector<Point>> holes;
};

struct BarrierLine {
    std::string line_id;
    std::vector<Point> points;
    bool active = true;
    std::string block_mode = "full_block";
    int priority = 3;
};

struct DirectionLine {
    std::string line_id;
    std::vector<Point> points;
    bool active = true;
    double ratio = 18.0;
    double influence_radius = 0.0;  // <=0 -> auto (curve corridor)
    int priority = 1;
    double core_radius = 0.0;       // <=0 -> auto
    std::string zone_id;
    std::string extend_mode = "auto";  // auto | none | tangent
    double transition = 0.0;           // <=0 -> auto
};

struct Config {
    int grid_resolution = 160;
    double power = 2.0;
    double search_radius = 10000.0;
    double interpolation_mask_radius = 0.0;
    bool interpolation_mask_use_control_points = false;
    int grid_smoothing_iterations = 2;
    bool smooth_across_barriers = false;
    bool use_extended_search = true;
    double barrier_blank_cells = 0.0;
    double barrier_buffer_distance = 0.0;
    bool barrier_buffer_applies_to_surface = true;
    bool barrier_buffer_auto = true;
    double barrier_partition_extension_cells = 0.0;
    bool barrier_extend_to_boundary = false;
    bool well_anchor_enabled = true;
    double well_anchor_radius = 0.0;
    double well_anchor_max_residual_fraction = 0.16;
    bool well_anchor_preserve_anisotropy = true;
    double direction_taper_plateau = 0.85;
    double direction_smoothing_strength = 1.8;
    double direction_perpendicular_strength = 1.0;
    double direction_corridor_strength = 1.0;
    double along_track_blend_strength = 0.0;
    double along_track_min_cell_g = 0.05;
    double along_track_exp_k = 6.0;
    bool anisotropic_fill = true;
    bool use_curve_direction_distance = true;
    double decluster_radius = 6500.0;
    double decluster_strength = 2.0;
    int gap_fill_iterations = 8;
    bool limit_interpolation_to_search_radius = true;
    int min_points = 3;
    int max_points = 12;
    std::optional<double> value_min = 0.0;
    std::optional<double> value_max = 1.0;
    double endpoint_tolerance = 1e-7;
    double boundary_margin_ratio = 0.02;
    double data_hull_buffer_meters = 0.0;
};

struct Result {
    std::vector<double> grid_x;  // len == config.grid_resolution (clamped)
    std::vector<double> grid_y;
    std::vector<double> grid_z;  // row-major |grid_y| x |grid_x|, NaN = nodata
    // Numeric surface-path diagnostics, keys matching the Python engine dict
    // (participating wells, region counts, barrier/LOS counters, anchor
    // stats, ...). String-valued Python entries are not reproduced.
    std::map<std::string, double> diagnostics;
};

// Raises std::invalid_argument with the Python engine's exact error text for
// the mirrored failure branches (fewer than 3 wells, no boundary polygon,
// boundary without vertices).
Result generate_constrained_idw(const std::vector<Well>& wells,
                                const std::vector<BoundaryPolygon>& boundaries,
                                const std::vector<BarrierLine>& barriers,
                                const std::vector<DirectionLine>& directions,
                                const Config& config);

}  // namespace pwb::mapping::constrained_idw
