#!/usr/bin/env bash
# deploy-native-product.sh — assemble a runnable native-product tree
# (native-product closure, task G).
#
#   scripts/cpp-migration/deploy-native-product.sh <build-dir> <dist-dir>
#
# Layout produced (Linux):
#   <dist>/bin/pwb-platform            launcher (env closure + exec)
#   <dist>/libexec/pwb-platform        the real binary (cmake install image)
#   <dist>/lib/                        non-system shared objects the binary
#                                      resolves (vendored QGIS + geo stack;
#                                      system Qt stays system Qt — one ABI,
#                                      same argument as the dev tree)
#   <dist>/qgis/                       QGIS prefix (plugins + resources +
#                                      share/proj + GDAL data), pointed at by
#                                      PWB_QGIS_PREFIX in the launcher
#
# The script ends with the deployed tree's own --self-check (dev fixtures
# are absent by design — fixture-gated checks report skipped, everything
# else must pass). Windows packaging keeps the same layout via
# windeployqt + the vendor bin/ tree (documented in the closure ledger;
# no online CI involved).
set -euo pipefail

if [ $# -ne 2 ]; then
    echo "usage: $0 <build-dir> <dist-dir>"; exit 2
fi
BuildDir="$(cd "$1" && pwd)"
DistDir="$2"
Exe="$BuildDir/bin/pwb-platform"
[ -x "$Exe" ] || Exe="$BuildDir/pwb-platform"
[ -x "$Exe" ] || { echo "pwb-platform not found under $1"; exit 2; }

QgisPrefix="${PALEO_QGIS_SDK_DIR:-}"
[ -n "$QgisPrefix" ] || QgisPrefix="$(cd "$BuildDir" && cmake -L . 2>/dev/null | awk -F= '/^PALEO_QGIS_SDK_DIR/{print $2}' | head -1)"
[ -n "$QgisPrefix" ] && [ -d "$QgisPrefix" ] || {
    echo "PALEO_QGIS_SDK_DIR not resolvable (pass it in the environment)"; exit 2; }

ProjData="${PWB_DEPLOY_PROJ_DATA:-}"
GdalData="${PWB_DEPLOY_GDAL_DATA:-}"

rm -rf "$DistDir"
mkdir -p "$DistDir/bin" "$DistDir/libexec" "$DistDir/lib" "$DistDir/qgis"

# ---- 1) binary + QGIS prefix ---------------------------------------------
cp "$Exe" "$DistDir/libexec/pwb-platform"
cp -R "$QgisPrefix/plugins" "$DistDir/qgis/plugins" 2>/dev/null || true
for resource in resources data share; do
    [ -d "$QgisPrefix/$resource" ] && cp -R "$QgisPrefix/$resource" "$DistDir/qgis/$resource"
done

# ---- 2) non-system .so closure (fixpoint over ldd) ------------------------
declare -A Copied
collect_closure() {
    local binary="$1"
    local deps
    deps=$(ldd "$binary" 2>/dev/null | awk '/=> \//{print $3} /^\/\//{print $1}' || true)
    for dep in $deps; do
        [ -f "$dep" ] || continue
        case "$dep" in
            /usr/lib/*|/usr/lib64/*|/lib/*|/lib64/*) continue ;;  # system ABI stays
        esac
        if [ -z "${Copied[$dep]:-}" ]; then
            Copied[$dep]=1
            cp -L "$dep" "$DistDir/lib/"
            collect_closure "$dep"
        fi
    done
}
echo "== collecting non-system .so closure"
collect_closure "$Exe"
# QGIS provider plugins resolve their own deps (gdal/proj already above).
echo "   copied $(printf '%s\n' "${!Copied[@]}" | wc -l) objects"

# ---- 3) proj/gdal data -----------------------------------------------------
if [ -n "$ProjData" ] && [ -d "$ProjData" ]; then
    mkdir -p "$DistDir/share"
    cp -R "$ProjData" "$DistDir/share/proj"
fi
if [ -n "$GdalData" ] && [ -d "$GdalData" ]; then
    mkdir -p "$DistDir/share"
    cp -R "$GdalData" "$DistDir/share/gdal"
fi

# ---- 4) launcher -----------------------------------------------------------
cat > "$DistDir/bin/pwb-platform" <<LAUNCHER
#!/usr/bin/env bash
# Generated by deploy-native-product.sh — product launcher.
Here="\$(cd "\$(dirname "\$0")/.." && pwd)"
export PWB_QGIS_PREFIX="\$Here/qgis"
export LD_LIBRARY_PATH="\$Here/lib\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
[ -d "\$Here/share/proj" ] && export PROJ_LIB="\$Here/share/proj" PROJ_DATA="\$Here/share/proj"
[ -d "\$Here/share/gdal" ] && export GDAL_DATA="\$Here/share/gdal"
exec "\$Here/libexec/pwb-platform" "\$@"
LAUNCHER
chmod +x "$DistDir/bin/pwb-platform"

# ---- 5) deployed-tree self-check (honest: fixture checks skip) -------------
echo "== deployed tree self-check"
QT_QPA_PLATFORM=offscreen "$DistDir/bin/pwb-platform" --self-check
echo "== deployed tree ready: $DistDir"
