#!/usr/bin/env bash
# deploy-native-product.sh — assemble a runnable native-product tree
# (native-product closure, task G).
#
#   scripts/cpp-migration/deploy-native-product.sh <build-dir> <dist-dir>
#
# Layout produced (Linux):
#   <dist>/bin/pwb-platform            launcher (env closure + exec)
#   <dist>/libexec/pwb-platform        the real binary (cmake install image)
#   <dist>/lib/                        non-system shared objects the binary
#                                      resolves (vendored QGIS + geo stack;
#                                      system Qt stays system Qt — one ABI,
#                                      same argument as the dev tree)
#   <dist>/qgis/                       QGIS prefix (plugins + resources +
#                                      share/proj + GDAL data), pointed at by
#                                      PWB_QGIS_PREFIX in the launcher
#
# The script ends with the deployed tree's own --self-check (dev fixtures
# are absent by design — fixture-gated checks report skipped, everything
# else must pass). Windows packaging keeps the same layout via
# windeployqt + the vendor bin/ tree (documented in the closure ledger;
# no online CI involved).
set -euo pipefail

if [ $# -ne 2 ]; then
    echo "usage: $0 <build-dir> <dist-dir>"; exit 2
fi
BuildDir="$(cd "$1" && pwd)"
DistDir="$2"
# CMake single-config generators drop the exe next to its object dir.
for candidate in \
    "$BuildDir/bin/pwb-platform" \
    "$BuildDir/apps/paleo_workbench_platform/pwb-platform" \
    "$BuildDir/pwb-platform"; do
    [ -x "$candidate" ] && Exe="$candidate" && break
done
[ -n "${Exe:-}" ] || { echo "pwb-platform not found under $1"; exit 2; }

QgisPrefix="${PALEO_QGIS_SDK_DIR:-}"
[ -n "$QgisPrefix" ] || QgisPrefix="$(cd "$BuildDir" && cmake -L . 2>/dev/null | awk -F= '/^PALEO_QGIS_SDK_DIR/{print $2}' | head -1)"
[ -n "$QgisPrefix" ] && [ -d "$QgisPrefix" ] || {
    echo "PALEO_QGIS_SDK_DIR not resolvable (pass it in the environment)"; exit 2; }

ProjData="${PWB_DEPLOY_PROJ_DATA:-}"
GdalData="${PWB_DEPLOY_GDAL_DATA:-}"

case "$DistDir" in
    ""|"/") echo "refusing to wipe unsafe DistDir '$DistDir'"; exit 2 ;;
esac
rm -rf "$DistDir"
mkdir -p "$DistDir/bin" "$DistDir/libexec" "$DistDir/lib" "$DistDir/qgis"

# ---- 1) binary + QGIS prefix ---------------------------------------------
cp "$Exe" "$DistDir/libexec/pwb-platform"
cp -R "$QgisPrefix/plugins" "$DistDir/qgis/plugins" 2>/dev/null || true
for resource in resources data share; do
    [ -d "$QgisPrefix/$resource" ] && cp -R "$QgisPrefix/$resource" "$DistDir/qgis/$resource"
done

# ---- 2) non-system .so closure (fixpoint over ldd) ------------------------
declare -A Copied
collect_closure() {
    local binary="$1"
    local deps
    deps=$(ldd "$binary" 2>/dev/null | awk '/=> \//{print $3} /^\/\//{print $1}' || true)
    for dep in $deps; do
        [ -f "$dep" ] || continue
        case "$dep" in
            /usr/lib/*|/usr/lib64/*|/lib/*|/lib64/*) continue ;;  # system ABI stays
        esac
        if [ -z "${Copied[$dep]:-}" ]; then
            Copied[$dep]=1
            cp -L "$dep" "$DistDir/lib/"
            collect_closure "$dep"
        fi
    done
}
echo "== collecting non-system .so closure"
collect_closure "$Exe"
# QGIS provider plugins resolve their own deps (gdal/proj already above).
echo "   copied $(printf '%s\n' "${!Copied[@]}" | wc -l) objects"

# ---- 3) proj/gdal data + gdal driver plugins -------------------------------
if [ -n "$ProjData" ] && [ -d "$ProjData" ]; then
    mkdir -p "$DistDir/share"
    cp -R "$ProjData" "$DistDir/share/proj"
fi
if [ -n "$GdalData" ] && [ -d "$GdalData" ]; then
    mkdir -p "$DistDir/share"
    cp -R "$GdalData" "$DistDir/share/gdal"
fi
# Optional: the geo SDK's gdal driver plugins (raster import/export reach).
for gdal_plugins in "${PWB_LOCAL_SDK:+$PWB_LOCAL_SDK/lib/gdalplugins}" \
                    "${PWB_DEPLOY_GDAL_PLUGINS:-}"; do
    if [ -n "$gdal_plugins" ] && [ -d "$gdal_plugins" ]; then
        mkdir -p "$DistDir/lib"
        cp -R "$gdal_plugins" "$DistDir/lib/gdalplugins"
        break
    fi
done

# ---- 4) launcher -----------------------------------------------------------
cat > "$DistDir/bin/pwb-platform" <<LAUNCHER
#!/usr/bin/env bash
# Generated by deploy-native-product.sh — product launcher.
Here="\$(cd "\$(dirname "\$0")/.." && pwd)"
export PWB_QGIS_PREFIX="\$Here/qgis"
export LD_LIBRARY_PATH="\$Here/lib\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
[ -d "\$Here/share/proj" ] && export PROJ_LIB="\$Here/share/proj" PROJ_DATA="\$Here/share/proj"
[ -d "\$Here/share/gdal" ] && export GDAL_DATA="\$Here/share/gdal"
[ -d "\$Here/lib/gdalplugins" ] && export GDAL_DRIVER_PATH="\$Here/lib/gdalplugins"
exec "\$Here/libexec/pwb-platform" "\$@"
LAUNCHER
chmod +x "$DistDir/bin/pwb-platform"

# ---- 4b) third-party license materials (cpp-close-12 release contract) ----
# The deployed package must carry the license texts of every runtime
# component: the vendored QGIS COPYING, the system Qt license set and a
# notice listing the remaining components (WLE SDK / ONNX Runtime are
# consumed from their SDK roots — their roots are collected here too when
# present). audit-licenses.sh verifies the result.
echo "== collecting third-party license materials"
DeployRepoRoot="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
mkdir -p "$DistDir/licenses"
# The vendor install tree has no COPYING at its root — fall back to the
# QGIS source tree (same variable the SDK admission consumes).
QgisCopying="${PALEO_QGIS_SOURCE_DIR:-$DeployRepoRoot/third_party/qgis}/COPYING"
if [ -f "$QgisPrefix/COPYING" ]; then
    cp "$QgisPrefix/COPYING" "$DistDir/licenses/QGIS-COPYING"
elif [ -f "$QgisCopying" ]; then
    cp "$QgisCopying" "$DistDir/licenses/QGIS-COPYING"
fi
if [ -d "${PWB_QT_PREFIX:-/usr}/share/licenses/qt6-base" ]; then
    cp -R "${PWB_QT_PREFIX:-/usr}/share/licenses/qt6-base" \
        "$DistDir/licenses/qt6-base" 2>/dev/null || true
fi
for extra_root in "${PWB_WLE_SDK_DIR:-$DeployRepoRoot/well-log-engine}" \
                  "${PWB_ORT_DIR:-}"; do
    if [ -n "$extra_root" ] && [ -f "$extra_root/LICENSE" ]; then
        cp "$extra_root/LICENSE" \
            "$DistDir/licenses/$(basename "$extra_root")-LICENSE"
    fi
done
cat > "$DistDir/licenses/THIRD-PARTY-LICENSES.md" <<'NOTICE'
# Third-party runtime components

This package ships a native C++ product. Runtime third-party components:

* Qt6 (system/vendor ABI, LGPL) — license set under `licenses/qt6-base/`.
* QGIS 4.2 (vendored SDK, GPL + exception) — `licenses/QGIS-COPYING*`.
* GDAL / PROJ / GEOS — consumed via the QGIS prefix; data dirs under `share/`.
* WLE well-log SDK and ONNX Runtime, when present in this package, carry
  their `LICENSE` files here.

Regenerate with scripts/cpp-migration/audit-licenses.sh (FAIL = do not ship).
NOTICE
echo "   license materials under $DistDir/licenses"

# ---- 5) deployed-tree self-check (honest: fixture checks skip) -------------
echo "== deployed tree self-check"
QT_QPA_PLATFORM=offscreen "$DistDir/bin/pwb-platform" --self-check
echo "== deployed tree ready: $DistDir"
