#pragma once

// AppContext — the application composition root's service layer
// (native-product closure, task B).
//
// Ownership + lifetime contract for the non-UI product services:
//   * ProjectSession (map/edit session) — created here, closed here in a
//     defined order while the MainWindow (canvas host) is still alive;
//   * the attribute AlgorithmRunner (kernel registration happens once
//     here, not per window);
//   * the project data-store handle shared by every operation that
//     resolves catalog versions.
//
// Composition flow of the native entry:
//   main.cpp -> bootstrap::run -> AppContext -> MainWindow -> services
// MainWindow consumes the context; small hosts/tests may embed one via the
// MainWindow convenience constructor. shutdown() is idempotent and safe to
// call from both the window teardown and the context destructor.

#include <memory>
#include <QString>
#include <QVector>

#include <pwb/application/project_session.hpp>

#include <pwb/app/product_capabilities.hpp>  // generated by cmake/PwbNativeProduct.cmake

#if defined(PWB_WITH_SEISMIC_ATTRIBUTES) && defined(PWB_WITH_DATA_INTEGRATION)
#include <pwb/application/algorithm_runner.hpp>
#endif

namespace pwb::application {
class PwbDataStore;
}

namespace pwb::app {

class AppContext {
public:
    AppContext();
    ~AppContext();

    AppContext(const AppContext&) = delete;
    AppContext& operator=(const AppContext&) = delete;

    // The map/edit session. Never null while the context lives.
    pwb::application::ProjectSession& session() const;

#if defined(PWB_WITH_SEISMIC_ATTRIBUTES) && defined(PWB_WITH_DATA_INTEGRATION)
    // The seismic attribute compute service (kernels registered here once).
    pwb::application::AlgorithmRunner& attributeRunner() const;
#endif

    // Shared project store handle (set by the project open/new flows).
    void setProjectStore(std::shared_ptr<pwb::application::PwbDataStore> store);
    std::shared_ptr<pwb::application::PwbDataStore> projectStore() const;

    // Ordered teardown: close the session (map tools unset, canvas
    // detached from layers, project layers dropped) while the host window
    // is still alive, then drop the service objects. Idempotent.
    void shutdown();

    // ---- capability discovery --------------------------------------------
    // One entry per compile-time capability, runtime-probed where the
    // build flag alone is not the whole truth.
    struct RuntimeCapability {
        QString id;
        QString title;
        capabilities::BuildClass cls;
        bool in_closure;   // compile-time link closure truth
        bool runtime_ok;   // runtime probe (services actually reachable)
        QString detail;
    };

    QVector<RuntimeCapability> capabilities() const;

    // Self-audit for self-check: every hard capability in this build has a
    // reachable service. ok=false lists the gaps.
    struct AuditEntry {
        QString id;
        bool ok;
        QString detail;
    };
    struct ServiceAudit {
        QVector<AuditEntry> entries;
        bool ok = false;
    };
    ServiceAudit auditServices() const;

private:
    void registerProductKernels();

    struct Impl;
    std::unique_ptr<Impl> impl_;
};

}  // namespace pwb::app
