#pragma once
// CONV-32 — store-driven workflow lifecycle engine: full C++ port of
// paleo_workbench/workflow/dag/engine.py class WorkflowEngine (validate ->
// create -> drive -> checkpoint -> resume/rerun/cancel). NOT the legacy
// in-memory Engine (engine.hpp) — that minimal executor stays untouched for
// its external consumers and is retired in a later wiring slice; this class
// is therefore named RunEngine (WorkflowEngine would collide conceptually
// with the library alias). Qt-free, Python-free.
//
// Semantics frozen against engine.py (see
// libs/workflow_engine/workflow_engine_tests/fixtures/
// workflow_engine_lifecycle_oracle.json, generated by
// tools/oracle/generate_workflow_engine_lifecycle_fixtures.py):
//   * create_run: validate_workflow_spec gate, slot defaults + slot schema
//     gate, spec-ordered NodeRuns, project stamping, store.save.
//   * run/resume: crash mapping (RUNNING -> INTERRUPTED, RUNNING nodes ->
//     PENDING "interrupted before completion; re-executing"), sequential
//     ready-batch drive, per-node checkpoint + on_update, fail-closed
//     finalize, project-match refusal, double-run guard.
//   * rerun: transitive-dependents closure, cache-identity carry-over of
//     provably identical SUCCEEDED work (receipt restamped), parent lineage.
//   * cancel: cooperative token cancel of the in-process run.
//   * _checkpoint: any persistence failure marks the run FAILED, inserts the
//     "__checkpoint__" NodeRun ("checkpoint persistence failed: <type>:
//     <msg>") and raises CheckpointFailed (fail-closed).
//
// Deviations from Python, frozen deliberately:
//   * _drive_parallel / submit_to_scheduler / scheduler-token sync are
//     DEFERRED: the drive loop is sequential regardless of
//     max_concurrency (the DAG executor is not TaskRuntime; CONV-07
//     precedent — see ledgers/07-decisions.md).
//   * Session-pointer merge/restore collapses to the ISessionContext seam
//     (default no-op; Python restores only same-process map documents).
//   * _register_cache_run (catalog provenance rail) is DEFERRED: reuse stays
//     store-limited, exactly like Python with a null catalog.
//   * external cancel is a const CancelToken* polled at engine boundaries
//     (loop head, guard, backoff waits) rather than Python's per-check
//     _ExternalSyncedToken duck-typing.
//   * Project identity compare is by Json value, not Python object identity
//     (`is`); probes in tests return distinct values.
//   * Node-function exceptions map onto the harness executor contract:
//     Cancelled -> status "cancelled" ("cancelled: <what>"); any other
//     std::exception -> status "failed" ("<type>: <what>").

#include <pwb/domain/json.hpp>
#include <pwb/workflow_spec/validation.hpp>   // BindEnv / bind_parameters / gates
#include <pwb/workflow_engine/engine.hpp>     // CancelToken / Cancelled (cooperative cancel)
#include <pwb/workflow_engine/receipt.hpp>    // ActionResultView / build_receipt seams
#include <pwb/workflow_engine/store.hpp>      // WorkflowRunStore / find_reusable_node

#include <cstdint>
#include <functional>
#include <map>
#include <memory>
#include <mutex>
#include <optional>
#include <stdexcept>
#include <string>
#include <vector>

namespace pwb::workflow_engine {

// engine.WorkflowValidationError — "workflow '<id>' invalid: <p1; p2; ...>"
// (distinct name from the legacy engine.hpp ValidationError).
struct WorkflowValidationError : std::runtime_error {
    std::vector<std::string> problems;
    WorkflowValidationError(std::string workflow_id,
                            std::vector<std::string> problems);
    ~WorkflowValidationError() override;
};

// engine.CheckpointFailed — the run store refused a checkpoint write; the
// run is already marked FAILED in memory (with the "__checkpoint__" node).
struct CheckpointFailed : std::runtime_error {
    explicit CheckpointFailed(const std::string& message)
        : std::runtime_error(message) {}
};

// harness.registry ActionSpec slice the engine reads (registry.get(...)).
// Python defaults mirrored: version "1.0", cacheable false, input_schema
// {} (treated as {"type":"object"}). `description` feeds receipts
// (node description wins when non-empty).
struct ActionInfo {
    std::string action_id;
    std::string version{"1.0"};
    bool cacheable = false;
    domain::Json input_schema = domain::Json::object();
    std::string description;
};

class IActionCatalog {
public:
    virtual ~IActionCatalog() = default;
    // nullopt == registry.get raising LookupError.
    [[nodiscard]] virtual std::optional<ActionInfo>
    get(const std::string& action_id) const = 0;
    // Registered ids (drives the validation risk map; Python registry).
    [[nodiscard]] virtual std::vector<std::string> ids() const = 0;
};

// Session-pointer seam (Python ActionContext.current_map_id /
// map_documents). Default is a no-op: pointer restore only ever worked
// same-process with live handles.
class ISessionContext {
public:
    virtual ~ISessionContext() = default;
    virtual void merge_session_pointers() {}
    virtual void restore_session_pointers(const domain::Json& /*outputs*/) {}
};

// engine.py _register_cache_run seam (L735): put a cacheable node's
// execution on the catalog provenance rail so reuse is traceable —
// "begin/complete like any other run". The engine calls it AFTER the
// receipt is built for every cacheable node with a cache identity (the
// Python gate: `identity is not None and catalog is not None`), and
// treats any rail failure as non-fatal (execution stays valid; reuse for
// that node is store-limited). cpp-close-02 completes the deferred half
// of the CONV-32 deferral; the catalog-read half (CatalogLike) is
// unchanged.
class CacheRunRail {
public:
    virtual ~CacheRunRail() = default;
    // Returns the rail's run id ("" == skipped); the engine records it on
    // receipt.catalog_run_id when non-empty. Throw to refuse (the engine
    // swallows and continues).
    [[nodiscard]] virtual std::string
    register_cache_run(const std::string& operation,
                       const std::vector<std::string>& input_version_ids,
                       const domain::Json& parameters,
                       const std::string& generator_version) = 0;
};

// engine.ActionContext slice the lifecycle engine consumes.
struct RunContext {
    std::string workspace_id;                 // context.workspace_id
    std::string project_path;                 // context.project_path ("" == None)
    domain::Json project_identity = nullptr;  // context.project (probe baseline)
    ISessionContext* session = nullptr;       // pointer merge/restore seam
    // Whitelisted $context values (validation.CONTEXT_BINDING_WHITELIST);
    // null/absent keys bind-fail "not available in this session".
    domain::Json context_values = domain::Json::object();
};

// engine.run(...) keyword options.
struct RunOptions {
    const CancelToken* external_cancel = nullptr;  // host/scheduler cancel
    std::function<domain::Json()> project_probe;   // live project identity
    bool reverify_cache = true;
    bool use_cache = true;
    std::function<void(const workflow_spec::WorkflowRun&)> on_update;
};

// Node body: bound params in, ActionResultView out (executor.execute
// contract). Throws Cancelled to cancel, anything else to fail the node.
// (RunNodeFunction — the legacy engine.hpp NodeFunction returns the legacy
// NodeResult and keeps its name.)
using RunNodeFunction =
    std::function<ActionResultView(const domain::Json& bound_params,
                                   const CancelToken& token)>;
using RunFunctionMap = std::map<std::string, RunNodeFunction>;

// Determinism seams (Python uuid4/time.time/wait).
using RunIdGenerator = std::function<std::string()>;
using BackoffWaiter = std::function<void(const CancelToken& token,
                                         double seconds)>;

class RunEngine {
public:
    // clock == nullptr -> wall clock; waiter == nullptr -> interruptible
    // sleep; id_gen == nullptr -> 16 random hex chars; env == nullptr ->
    // empty environment identity (production injects host values);
    // artifact_catalog == nullptr -> store-limited cache reuse.
    RunEngine(const IActionCatalog& catalog, RunFunctionMap functions,
              WorkflowRunStore& store, Clock clock = nullptr,
              BackoffWaiter waiter = nullptr,
              EnvironmentProvider env = nullptr,
              const CatalogLike* artifact_catalog = nullptr,
              RunIdGenerator id_gen = nullptr,
              CacheRunRail* cache_run_rail = nullptr);
    ~RunEngine();
    RunEngine(const RunEngine&) = delete;
    RunEngine& operator=(const RunEngine&) = delete;

    // engine.create_run — validates (WorkflowValidationError), materializes
    // slot defaults + slot schema gate, stamps project fields from context,
    // persists. run_id/now come from the injected seams.
    [[nodiscard]] workflow_spec::WorkflowRun
    create_run(const workflow_spec::WorkflowSpec& spec,
               domain::Json slot_values, const RunContext* context = nullptr);

    // engine.run — COMPLETED/CANCELLED runs return untouched; RUNNING runs
    // resume through the crash mapping. Raises WorkflowValidationError
    // (project mismatch / double-run), CheckpointFailed (persistence),
    // StoreError (load).
    workflow_spec::WorkflowRun run(const std::string& run_id,
                                   const RunContext* context = nullptr,
                                   const RunOptions& options = {});

    // engine.resume — load + project match, then run().
    workflow_spec::WorkflowRun resume(const std::string& run_id,
                                      const RunContext* context = nullptr,
                                      const RunOptions& options = {});

    // engine.rerun — new run re-executing `from_nodes` + transitive
    // dependents; provably identical SUCCEEDED nodes carry over.
    [[nodiscard]] workflow_spec::WorkflowRun
    rerun(const std::string& run_id,
          const std::vector<std::string>& from_nodes = {},
          domain::Json slot_overrides = domain::Json::object(),
          const RunContext* context = nullptr,
          const RunOptions& options = {});

    // engine.cancel — True iff an in-process run was signalled.
    bool cancel(const std::string& run_id);

private:
    struct ActiveRun {
        std::string workflow_id;
        std::shared_ptr<CancelToken> token;
    };

    void drive(workflow_spec::WorkflowRun& run, const RunContext* context,
               CancelToken& token, const domain::Json& project_identity,
               const RunOptions& options);
    void execute_node(workflow_spec::WorkflowRun& run,
                      const std::string& node_id, const RunContext* context,
                      CancelToken& token, const RunOptions& options);
    // nullopt == Python None (nothing left at all).
    [[nodiscard]] std::optional<std::vector<std::string>>
    ready_batch(workflow_spec::WorkflowRun& run, int limit);
    void skip_dependents(workflow_spec::WorkflowRun& run,
                         const std::string& node_id, const std::string& reason);
    void cancel_pending(workflow_spec::WorkflowRun& run,
                        const std::string& reason);
    void finalize(workflow_spec::WorkflowRun& run);
    void prepare_interrupted(workflow_spec::WorkflowRun& run);
    void checkpoint(workflow_spec::WorkflowRun& run);
    void check_project_match(const workflow_spec::WorkflowRun& run,
                             const RunContext* context);
    [[nodiscard]] std::optional<std::string>
    cache_identity(const workflow_spec::NodeSpec& node,
                   const workflow_spec::WorkflowRun& run,
                   const RunContext* context);
    void finish_node(workflow_spec::NodeRun& node_run,
                     workflow_spec::NodeState state,
                     std::optional<std::string> error = std::nullopt,
                     std::optional<std::string> skip_reason = std::nullopt,
                     std::optional<std::string> action_status = std::nullopt);
    void notify(const workflow_spec::WorkflowRun& run,
                const RunOptions& options) const;
    [[nodiscard]] static workflow_spec::BindEnv
    bind_env(const workflow_spec::WorkflowRun& run, const RunContext* context);
    [[nodiscard]] double now();

    const IActionCatalog& catalog_;
    RunFunctionMap functions_;
    WorkflowRunStore& store_;
    Clock clock_;
    BackoffWaiter waiter_;
    EnvironmentProvider env_;
    const CatalogLike* artifact_catalog_;
    CacheRunRail* cache_run_rail_;
    RunIdGenerator id_gen_;

    std::mutex active_mutex_;
    std::map<std::string, ActiveRun> active_;
};

// Python _is_resource_shed — governor admission refusal markers
// (case-insensitive substring).
[[nodiscard]] bool is_resource_shed(const std::optional<std::string>& error);

// Python _condition_node_ids — every node referenced by a condition tree.
[[nodiscard]] std::vector<std::string>
condition_node_ids(const workflow_spec::NodeCondition& condition);

// Python _evaluate_condition — declarative evaluation, never throws.
[[nodiscard]] bool
evaluate_condition(const workflow_spec::NodeCondition& condition,
                   const workflow_spec::WorkflowRun& run);

}  // namespace pwb::workflow_engine
