#!/usr/bin/env bash
# Vendored GDAL superbuild: compile PROJ + GDAL (and the osgeo Python
# bindings) from the third_party/ submodules into an in-project prefix.
# Nothing is searched from the system except ubiquitous build deps
# (sqlite3/zlib headers, cmake, ninja, swig, a C++17 compiler).
#
# Result layout:
#   native/gdal-vendored/build/{proj,gdal}   compile trees (gitignored)
#   native/gdal-vendored/install             the prefix (libgdal, proj, osgeo)
#   native/gdal-vendored/install/env.sh      source this to use the build
#
# Usage: scripts/build_vendored_gdal.sh [python]   (default: venv/active python)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PREFIX="${ROOT}/native/gdal-vendored/install"
BUILD="${ROOT}/native/gdal-vendored/build"
PYTHON="${1:-${PYTHON:-python}}"
JOBS="${CMAKE_BUILD_PARALLEL_LEVEL:-$(nproc)}"

command -v cmake >/dev/null || { echo "cmake not found" >&2; exit 1; }
command -v ninja >/dev/null || { echo "ninja not found" >&2; exit 1; }
# Bindings must be generated by a modern SWIG (>= 4.1). Pre-4.1 SWIG emits
# PyInt_Check typemaps that do not compile against Python 3, and stale swig
# wrappers earlier on PATH win CMake's find_program. Always install the swig
# wheel into the target env and pin CMake to that exact executable; also drop
# any previously generated wrappers so a re-run after a SWIG change regenerates.
"$PYTHON" -m pip install -q swig
SWIG_BIN="$("$PYTHON" -c 'import pathlib, sys; print(pathlib.Path(sys.executable).parent / "swig")')"
[ -x "${SWIG_BIN}" ] || { echo "swig not found at ${SWIG_BIN}" >&2; exit 1; }
echo "Using SWIG: ${SWIG_BIN} ($("${SWIG_BIN}" -version | sed -n 2p))"
rm -f "${BUILD}/gdal/swig/python/extensions/"*_wrap.cpp "${BUILD}/gdal/swig/python/extensions/"*_wrap.c

# v3.10.3 python typemaps carry Python-2 remnants (``PyInt_Check``,
# ``PyInt_FromLong``). Modern Python headers no longer declare the PyInt_*
# family, so the generated wrappers do not compile. Upstream master replaced
# them with the PyLong_* family; apply the same minimal edits in the
# submodule worktree (no submodule commit).
TYPEMAPS="${ROOT}/third_party/gdal/swig/include/python/typemaps_python.i"
if grep -q "PyInt_" "${TYPEMAPS}"; then
  sed -i 's/ || PyInt_Check($input)//g; s/PyInt_FromLong/PyLong_FromLong/g; s/PyInt_AsLong/PyLong_AsLong/g' "${TYPEMAPS}"
  echo "Patched Python-2 PyInt_* remnants in $(basename "${TYPEMAPS}")"
fi

mkdir -p "${BUILD}/proj" "${BUILD}/gdal" "${PREFIX}"

# ---------------------------------------------------------------- PROJ
echo "== PROJ =="
cmake -S "${ROOT}/third_party/proj" -B "${BUILD}/proj" -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
  -DBUILD_TESTING=OFF \
  -DENABLE_CURL=OFF \
  -DENABLE_TIFF=OFF \
  -DBUILD_PROJSYNC=OFF \
  -DBUILD_PROJINFO=ON \
  -DUSE_PKG_CONFIG=ON
cmake --build "${BUILD}/proj" -j "${JOBS}"
cmake --install "${BUILD}/proj"

# ---------------------------------------------------------------- GDAL
echo "== GDAL =="
gdal_opts=(
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_INSTALL_PREFIX="${PREFIX}"
  -DCMAKE_PREFIX_PATH="${PREFIX}"
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON
  -DBUILD_TESTING=OFF
  # Only our drivers: internal libtiff/libgeotiff/libjson etc.
  -DGDAL_USE_EXTERNAL_LIBS=OFF
  -DGDAL_BUILD_OPTIONAL_DRIVERS=OFF
  -DOGR_BUILD_OPTIONAL_DRIVERS=OFF
  -DGDAL_ENABLE_DRIVER_GTIFF=ON
  -DGDAL_ENABLE_DRIVER_COG=ON
  -DGDAL_ENABLE_DRIVER_VRT=ON
  -DOGR_ENABLE_DRIVER_GEOJSON=ON
  -DOGR_ENABLE_DRIVER_CSV=ON
  -DOGR_ENABLE_DRIVER_ESRI_SHAPEFILE=ON
  # Python bindings compiled against this libgdal, never the system one.
  -DBUILD_PYTHON_BINDINGS=ON
  "-DPython_EXECUTABLE=${PYTHON}"
  -DGDAL_PYTHON_BINDINGS_WITHOUT_NUMPY=ON
  -DBUILD_PYTHON_WHEEL=OFF
  -DBUILD_CSHARP_BINDINGS=OFF
  -DBUILD_JAVA_BINDINGS=OFF
)
cmake -S "${ROOT}/third_party/gdal" -B "${BUILD}/gdal" -G Ninja "${gdal_opts[@]}"
cmake --build "${BUILD}/gdal" -j "${JOBS}"
cmake --install "${BUILD}/gdal"

# ---------------------------------------------------------------- env
GDAL_VERSION="$("${PREFIX}/bin/gdal-config" --version)"
cat > "${PREFIX}/env.sh" <<EOF
# Source to use the vendored GDAL (${GDAL_VERSION}) instead of the system one.
# NOTE: PROJ_DATA is deliberately NOT exported. The vendored libproj has its
# install prefix compiled in and finds <prefix>/share/proj on its own; forcing
# PROJ_DATA globally would break rasterio wheels (they bundle a newer libproj
# whose proj.db layout is incompatible with the vendored one).
export GDAL_VENDORED_PREFIX="${PREFIX}"
export GDAL_DATA="${PREFIX}/share/gdal"
export LD_LIBRARY_PATH="${PREFIX}/lib:\${LD_LIBRARY_PATH:-}"
EOF

# Bindings install under <prefix>/lib/pythonX.Y/site-packages (CMake's
# Python install scheme). Locate it and prepend to PYTHONPATH.
OSGEO_SITE="$(find "${PREFIX}/lib" -maxdepth 4 -type d -name site-packages -path "*python*" 2>/dev/null | head -1)"
if [ -n "${OSGEO_SITE}" ] && [ -d "${OSGEO_SITE}/osgeo" ]; then
  echo "export PYTHONPATH=\"${OSGEO_SITE}:\${PYTHONPATH:-}\"" >> "${PREFIX}/env.sh"
  echo "osgeo exposed via PYTHONPATH=${OSGEO_SITE}"
else
  echo "WARNING: osgeo bindings not found under ${PREFIX}/lib" >&2
  exit 1
fi

echo "OK: vendored GDAL ${GDAL_VERSION} at ${PREFIX}"
