# PwbInstall.cmake — native packaging skeleton (opt-in, OFF by default).
#
# Engineering hardening only (branch cpp-build-packaging-hardening). This file
# adds NO install rules unless PWB_ENABLE_PACKAGING=ON, so the other six
# worktrees are unaffected. Every artifact is optional: absent dirs/targets
# are reported and skipped, never turned into a FATAL_ERROR.
#
# Layout produced when enabled (relative to CMAKE_INSTALL_PREFIX):
#   bin/pwb-platform[.exe]                 application executable
#   bin/*.dll                              runtime closure: QGIS + Qt + MSVC CRT (Windows)
#   bin/platforms|imageformats|styles/     Qt plugins (Windows)
#   lib/                                   shared libraries (Linux: libpwb*.so; empty on Windows)
#   share/paleo-workbench/resources/       application resources
#   share/paleo-workbench/templates/       document templates
#   share/paleo-workbench/icons/           application icons
#   share/paleo-workbench/schema/          JSON schemas
#   share/paleo-workbench/pwb-package-layout.txt   this manifest
#   bin/pwb-diagnose[.exe]                 optional install/diagnostic helper
#
# Public API (all functions are safe to call even when packaging is OFF; they
# become no-ops via the guard below):
#   pwb_install_native_targets()   install pwb-platform + any present native target
#   pwb_install_resources()        install repo + QGIS vendor resource dirs that exist
#   pwb_install_qt_plugins()       deploy Qt platforms/imageformats/styles dirs
#   pwb_install_runtime_dlls(t)    collect + install runtime DLLs next to the binary
#   pwb_install_diagnostic()       install pwb-diagnose (when built) + layout manifest
#   pwb_install_all()              convenience: call every installer above

include_guard(GLOBAL)

if(NOT PWB_ENABLE_PACKAGING)
    # Opt-out: define nothing, register nothing. The other worktrees that do
    # not set this switch keep their configure graphs byte-for-byte identical.
    return()
endif()

include(GNUInstallDirs)

message(STATUS "PwbInstall: native packaging enabled (PWB_ENABLE_PACKAGING=ON)")

# --------------------------------------------------------------------------- #
# Debug-DLL filter: explicit allow/deny list (never a naive "d.dll" regex).
#
# A naive `-notmatch "d\\.dll$` test would wrongly drop zstd.dll (it ends in
# "d.dll" but is a release library). We instead keep every DLL and only DENY
# the specific debug-suffixed runtimes we know about.
# --------------------------------------------------------------------------- #
function(pwb_is_debug_dll name out_var)
    string(TOLOWER "${name}" _l)
    set(_debug FALSE)
    # MSVC debug CRT / STL runtimes (always suffixed 'd'):
    if(_l MATCHES "^(msvcp|vcruntime|ucrtbase|concrt)140.*d\\.dll$")
        set(_debug TRUE)
    # Qt debug shared libraries (Qt6<Module>d.dll / Qt5<Module>d.dll):
    elseif(_l MATCHES "^qt[56].+d\\.dll$")
        set(_debug TRUE)
    endif()
    set(${out_var} "${_debug}" PARENT_SCOPE)
endfunction()

# --------------------------------------------------------------------------- #
# Runtime layout manifest — documents the layout this module installs.
# --------------------------------------------------------------------------- #
function(pwb_write_layout_manifest out_file)
    set(_content
"paleo-workbench native package layout (generated by cmake/PwbInstall.cmake)
=========================================================================
This manifest documents the install tree produced when PWB_ENABLE_PACKAGING=ON.

  bin/pwb-platform[.exe]                 application executable
  bin/*.dll                              runtime closure: QGIS + Qt + MSVC CRT (Windows)
  bin/platforms/                        Qt platform plugin (qwindows)
  bin/imageformats/                     Qt image format plugins
  bin/styles/                           Qt style plugins
  lib/                                  shared libraries (Linux: libpwb*.so; empty on Windows)
  share/paleo-workbench/resources/      application resources
  share/paleo-workbench/templates/      document templates
  share/paleo-workbench/icons/          application icons
  share/paleo-workbench/schema/         JSON schemas
  share/paleo-workbench/pwb-package-layout.txt   this manifest
  bin/pwb-diagnose[.exe]                optional install/diagnostic helper

Notes:
  * All paths are relative to the install prefix (CMAKE_INSTALL_PREFIX).
  * On Windows the runtime closure lives next to the executable under bin/.
  * On Linux, INSTALL_RPATH is $ORIGIN/../lib (placeholder until a real Linux
    package is exercised); BUILD_WITH_INSTALL_RPATH is OFF.
  * Every artifact above is optional; absent sources are skipped at configure
    time and reported via PwbInstall: STATUS messages.
")
    file(WRITE "${out_file}" "${_content}")
endfunction()

# --------------------------------------------------------------------------- #
# pwb_install_native_targets() — install the platform executable (and any other
# native target that actually exists). TARGET-guarded so an OFF feature graph
# cannot fail the configure.
# --------------------------------------------------------------------------- #
function(pwb_install_native_targets)
    if(TARGET pwb-platform)
        install(TARGETS pwb-platform
                RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
        message(STATUS "PwbInstall: install rule registered for target pwb-platform")
    else()
        message(STATUS "PwbInstall: target pwb-platform does not exist — skipping executable install")
    endif()

    # Any other native helper target that may have been built.
    foreach(_t pwb-diagnose)
        if(TARGET ${_t})
            install(TARGETS ${_t}
                    RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
            message(STATUS "PwbInstall: install rule registered for target ${_t}")
        endif()
    endforeach()
endfunction()

# --------------------------------------------------------------------------- #
# pwb_install_resources() — install existing repo resource dirs + the QGIS
# vendor resources dir (when present). Absent dirs are reported and skipped.
# --------------------------------------------------------------------------- #
function(pwb_install_resources)
    # Repo-side resource trees (relative to the source root).
    set(_repo_resources
        "paleo_workbench/resources"
        "paleo_workbench/templates"
        "paleo_workbench/icons")
    foreach(_rel IN LISTS _repo_resources)
        set(_src "${CMAKE_CURRENT_SOURCE_DIR}/${_rel}")
        if(EXISTS "${_src}")
            install(DIRECTORY "${_src}"
                    DESTINATION "${CMAKE_INSTALL_DATADIR}/paleo-workbench"
                    FILES_MATCHING
                    PATTERN "*"
                    PATTERN "*.py" EXCLUDE
                    PATTERN "*.pyc" EXCLUDE
                    PATTERN "__pycache__" EXCLUDE
                    PATTERN ".git" EXCLUDE)
            message(STATUS "PwbInstall: installing resource dir ${_rel}")
        else()
            message(STATUS "PwbInstall: resource dir ${_rel} absent — skipped")
        endif()
    endforeach()

    # JSON schema dir: look for any directory named like *schema* under
    # paleo_workbench (optional; reported + skipped when absent).
    file(GLOB _schema_dirs "${CMAKE_CURRENT_SOURCE_DIR}/paleo_workbench/*schema*")
    foreach(_sd IN LISTS _schema_dirs)
        if(IS_DIRECTORY "${_sd}")
            install(DIRECTORY "${_sd}"
                    DESTINATION "${CMAKE_INSTALL_DATADIR}/paleo-workbench"
                    PATTERN ".git" EXCLUDE)
            message(STATUS "PwbInstall: installing schema dir ${_sd}")
        endif()
    endforeach()

    # QGIS vendor resources under the bridge output (only when the SDK is in play).
    if(DEFINED PALEO_QGIS_SDK_DIR AND EXISTS "${PALEO_QGIS_SDK_DIR}/resources")
        install(DIRECTORY "${PALEO_QGIS_SDK_DIR}/resources"
                DESTINATION "${CMAKE_INSTALL_DATADIR}/paleo-workbench"
                PATTERN ".git" EXCLUDE)
        message(STATUS "PwbInstall: installing QGIS vendor resources dir")
    else()
        message(STATUS "PwbInstall: QGIS vendor resources absent — skipped")
    endif()
endfunction()

# --------------------------------------------------------------------------- #
# pwb_install_qt_plugins() — deploy Qt platforms/imageformats/styles dirs from
# the Qt prefix. Tolerates a missing prefix and missing individual dirs.
# --------------------------------------------------------------------------- #
function(pwb_install_qt_plugins)
    if(NOT WIN32)
        message(STATUS "PwbInstall: Qt plugin deployment is Windows-focused; "
                       "Linux uses the system Qt — skipped")
        return()
    endif()
    if(NOT DEFINED PWB_QT_PREFIX OR NOT EXISTS "${PWB_QT_PREFIX}")
        message(STATUS "PwbInstall: PWB_QT_PREFIX not set/exists — "
                       "skipping Qt plugin deployment")
        return()
    endif()

    set(_plugins platforms imageformats styles)
    foreach(_p IN LISTS _plugins)
        set(_src "${PWB_QT_PREFIX}/plugins/${_p}")
        if(EXISTS "${_src}")
            install(DIRECTORY "${_src}"
                    DESTINATION "${CMAKE_INSTALL_BINDIR}"
                    FILES_MATCHING
                    PATTERN "*.dll"
                    PATTERN "*.so"
                    PATTERN "*.dylib")
            message(STATUS "PwbInstall: deploying Qt plugin dir ${_p}")
        else()
            message(STATUS "PwbInstall: Qt plugin dir ${_p} not found at "
                           "${_src} — skipped")
        endif()
    endforeach()
endfunction()

# --------------------------------------------------------------------------- #
# pwb_install_runtime_dlls(<exe_target>) — collect the runtime DLL closure of
# the installed executable from the QGIS runtime dir, the Qt bin dir and the
# MSVC redistributable dir; filter DEBUG DLLs via an explicit allow/deny list;
# install the survivors next to the binary.
# --------------------------------------------------------------------------- #
function(pwb_install_runtime_dlls exe_target)
    if(NOT WIN32)
        message(STATUS "PwbInstall: no runtime DLLs on non-Windows — skipped")
        return()
    endif()
    if(NOT TARGET ${exe_target})
        message(STATUS "PwbInstall: ${exe_target} not built — "
                       "skipping runtime DLL collection")
        return()
    endif()

    set(_dirs "")
    if(DEFINED PALEO_QGIS_RUNTIME AND EXISTS "${PALEO_QGIS_RUNTIME}")
        list(APPEND _dirs "${PALEO_QGIS_RUNTIME}")
    else()
        message(STATUS "PwbInstall: QGIS runtime dir unavailable — skipping QGIS DLLs")
    endif()
    if(DEFINED PWB_QT_RUNTIME AND EXISTS "${PWB_QT_RUNTIME}")
        list(APPEND _dirs "${PWB_QT_RUNTIME}")
    else()
        message(STATUS "PwbInstall: Qt runtime dir unavailable — skipping Qt DLLs")
    endif()

    # MSVC redistributable CRT dir: search the installed VS layout for the
    # Microsoft.VC143.CRT directory (version-independent glob).
    set(_msvc_redist "")
    set(_vs_root "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Redist/MSVC")
    if(EXISTS "${_vs_root}")
        file(GLOB _crt_candidates "${_vs_root}/*/x64/Microsoft.VC143.CRT")
        if(_crt_candidates)
            list(GET _crt_candidates 0 _msvc_redist)
            list(APPEND _dirs "${_msvc_redist}")
        else()
            message(STATUS "PwbInstall: MSVC redist CRT dir not found under "
                           "${_vs_root} — skipping CRT DLLs")
        endif()
    else()
        message(STATUS "PwbInstall: MSVC redist root absent — skipping CRT DLLs")
    endif()

    foreach(_dir IN LISTS _dirs)
        file(GLOB _dlls "${_dir}/*.dll")
        set(_keep "")
        foreach(_dll IN LISTS _dlls)
            get_filename_component(_name "${_dll}" NAME)
            pwb_is_debug_dll("${_name}" _is_debug)
            if(_is_debug)
                message(STATUS "PwbInstall: skipping debug DLL ${_name}")
            else()
                list(APPEND _keep "${_dll}")
            endif()
        endforeach()
        if(_keep)
            install(FILES ${_keep} DESTINATION "${CMAKE_INSTALL_BINDIR}")
            list(LENGTH _keep _n)
            message(STATUS "PwbInstall: installing ${_n} runtime DLL(s) from ${_dir}")
        else()
            message(STATUS "PwbInstall: no release DLLs found in ${_dir}")
        endif()
    endforeach()
endfunction()

# --------------------------------------------------------------------------- #
# pwb_install_diagnostic() — install the layout manifest and the pwb-diagnose
# helper (when it was built). The manifest is always installed so the package
# self-documents even with no executable present.
# --------------------------------------------------------------------------- #
function(pwb_install_diagnostic)
    set(_manifest "${CMAKE_CURRENT_BINARY_DIR}/pwb-package-layout.txt")
    pwb_write_layout_manifest("${_manifest}")
    install(FILES "${_manifest}"
            DESTINATION "${CMAKE_INSTALL_DATADIR}/paleo-workbench")
    message(STATUS "PwbInstall: install rule registered for package layout manifest")

    if(TARGET pwb-diagnose)
        install(TARGETS pwb-diagnose
                RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
        message(STATUS "PwbInstall: install rule registered for pwb-diagnose")
    else()
        message(STATUS "PwbInstall: pwb-diagnose not built "
                       "(PWB_BUILD_PLATFORM=OFF) — diagnostic executable skipped; "
                       "layout manifest still installed")
    endif()
endfunction()

# --------------------------------------------------------------------------- #
# pwb_install_all() — convenience entry point used by the root CMakeLists.txt.
# --------------------------------------------------------------------------- #
function(pwb_install_all)
    pwb_install_native_targets()
    pwb_install_resources()
    pwb_install_qt_plugins()
    pwb_install_runtime_dlls(pwb-platform)
    pwb_install_diagnostic()

    # Linux RPATH: placeholder until a real Linux package is exercised.
    if(UNIX AND NOT APPLE)
        set(CMAKE_INSTALL_RPATH "$ORIGIN/../lib" CACHE STRING
            "Runtime search path for the native package (placeholder)" FORCE)
        set(CMAKE_BUILD_WITH_INSTALL_RPATH OFF CACHE BOOL
            "Do not embed the install RPATH at build time (placeholder)" FORCE)
        message(STATUS "PwbInstall: Linux INSTALL_RPATH=$ORIGIN/../lib (placeholder)")
    endif()
endfunction()

# Activate the skeleton. The functions above are also safe to call individually.
pwb_install_all()
